import digitalSecurityImg from "@/assets/lessons/digital-security.jpg";
import financialBudgetingImg from "@/assets/lessons/financial-budgeting.jpg";
import healthWellnessImg from "@/assets/lessons/health-wellness.jpg";
import careerSkillsImg from "@/assets/lessons/career-skills.jpg";
import cookingNutritionImg from "@/assets/lessons/cooking-nutrition.jpg";
import socialSkillsImg from "@/assets/lessons/social-skills.jpg";

export interface LessonStep {
  type: "info" | "quiz" | "drag";
  title: string;
  content?: string;
  image?: string;
  question?: string;
  options?: string[];
  correct?: number;
  explanation?: string;
  instruction?: string;
  items?: { id: string; text: string; order: number }[];
  mascotMsg: string;
}

export interface Lesson {
  id: number;
  title: string;
  description: string;
  steps: LessonStep[];
}

export interface Course {
  id: string;
  label: string;
  emoji: string;
  description: string;
  lessons: Lesson[];
  image?: string;
}

export const COURSES: Course[] = [
  {
    id: "tech",
    label: "Digital Literacy",
    emoji: "💻",
    description: "Internet safety, using devices, online tools, email",
    image: digitalSecurityImg,
    lessons: [
      {
        id: 1,
        title: "Staying Safe Online",
        description: "Learn how to protect yourself on the internet",
        steps: [
          {
            type: "info",
            title: "Why Online Safety Matters",
            content: "Every time you go online, you leave a digital footprint. Hackers, scammers, and advertisers can use your data. Learning to protect yourself is one of the most important digital skills you can have.",
            image: digitalSecurityImg,
            mascotMsg: "Let's learn how to stay safe on the internet! 🛡️",
          },
          {
            type: "quiz",
            title: "Password Strength",
            question: "Which of these is the STRONGEST password?",
            options: ["password123", "MyDog'sName", "j7$kL9!mQ2@xP", "12345678"],
            correct: 2,
            explanation: "A strong password uses a mix of uppercase, lowercase, numbers, and symbols. It should be at least 12 characters and not based on personal info.",
            mascotMsg: "Time to test your knowledge! 🔐",
          },
          {
            type: "info",
            title: "Two-Factor Authentication (2FA)",
            content: "2FA adds an extra layer of security. Even if someone steals your password, they can't access your account without the second factor — usually a code sent to your phone or generated by an app like Google Authenticator.",
            mascotMsg: "This is a game-changer for security! 📱",
          },
          {
            type: "drag",
            title: "Security Best Practices",
            instruction: "Put these security steps in order of priority:",
            items: [
              { id: "a", text: "Use unique passwords for each account", order: 1 },
              { id: "b", text: "Enable two-factor authentication", order: 2 },
              { id: "c", text: "Keep software updated", order: 3 },
              { id: "d", text: "Use a password manager", order: 4 },
            ],
            mascotMsg: "Order these from most to least important! 🧩",
          },
          {
            type: "quiz",
            title: "Phishing Awareness",
            question: "Which is a sign of a phishing email?",
            options: [
              "It comes from your bank's official domain",
              "It asks you to urgently click a link to verify your identity",
              "It has proper grammar and spelling",
              "It was expected based on a recent action you took",
            ],
            correct: 1,
            explanation: "Phishing emails create urgency to trick you into clicking malicious links. Always verify sender addresses and never click suspicious links.",
            mascotMsg: "Last question — you've got this! 🎯",
          },
        ],
      },
      {
        id: 2,
        title: "Using Email Effectively",
        description: "Master email etiquette and organization",
        steps: [
          {
            type: "info",
            title: "Email Basics",
            content: "Email is still the primary form of professional communication. A well-crafted email can open doors, while a poorly written one can close them. Let's learn the essentials of email communication.",
            mascotMsg: "Email skills are super important! 📧",
          },
          {
            type: "quiz",
            title: "Email Etiquette",
            question: "What should you always include in a professional email?",
            options: [
              "Emojis to be friendly",
              "A clear subject line",
              "Your entire life story",
              "Multiple fonts and colors",
            ],
            correct: 1,
            explanation: "A clear subject line helps the recipient understand the purpose of your email immediately. It's the first thing they see!",
            mascotMsg: "Think about what makes an email easy to read! 🤔",
          },
          {
            type: "info",
            title: "Managing Your Inbox",
            content: "Use the '4 D's method': Delete (spam/irrelevant), Do (takes under 2 minutes), Delegate (forward to the right person), or Defer (schedule for later). This keeps your inbox manageable.",
            mascotMsg: "Pro tip for inbox zero! 📋",
          },
          {
            type: "drag",
            title: "Parts of a Professional Email",
            instruction: "Put these email components in the correct order:",
            items: [
              { id: "a", text: "Subject line", order: 1 },
              { id: "b", text: "Greeting (Dear/Hi)", order: 2 },
              { id: "c", text: "Body (main message)", order: 3 },
              { id: "d", text: "Sign-off and signature", order: 4 },
            ],
            mascotMsg: "Structure matters! Put these in order! 📝",
          },
          {
            type: "quiz",
            title: "CC vs BCC",
            question: "When should you use BCC (Blind Carbon Copy)?",
            options: [
              "When you want everyone to see all recipients",
              "When sending to a large group where privacy matters",
              "Only for your boss",
              "Never — it's considered rude",
            ],
            correct: 1,
            explanation: "BCC protects recipients' email addresses from being visible to others. It's essential for mass emails and protecting privacy.",
            mascotMsg: "Almost done with email mastery! 🎉",
          },
        ],
      },
      {
        id: 3,
        title: "Navigating Social Media Safely",
        description: "Privacy settings, digital footprint, and responsible posting",
        steps: [
          {
            type: "info",
            title: "Your Digital Footprint",
            content: "Everything you post, like, share, or comment on creates a permanent digital footprint. Future employers, schools, and others can find this information. Think before you post!",
            mascotMsg: "Your online presence matters more than you think! 🌐",
          },
          {
            type: "quiz",
            title: "Privacy Settings",
            question: "What should you do FIRST when creating a new social media account?",
            options: [
              "Post your first photo",
              "Add all your friends",
              "Review and adjust privacy settings",
              "Share your location",
            ],
            correct: 2,
            explanation: "Always review privacy settings first. Set your profile to private, limit who can see your posts, and control who can tag you.",
            mascotMsg: "Privacy first! Always! 🔒",
          },
          {
            type: "info",
            title: "Recognizing Misinformation",
            content: "Before sharing news: Check the source (is it reputable?), look for the story on other outlets, check the date (is it current?), and read beyond the headline. If it sounds too outrageous, it might be fake.",
            mascotMsg: "Be a critical thinker online! 🧠",
          },
          {
            type: "quiz",
            title: "Safe Sharing",
            question: "Which of these is safe to share publicly on social media?",
            options: [
              "Your home address",
              "A photo of your vacation after you return",
              "Your daily routine and schedule",
              "Pictures of your credit card",
            ],
            correct: 1,
            explanation: "Sharing vacation photos after returning is safe. Never share locations in real-time, personal documents, or daily routines that could be used against you.",
            mascotMsg: "You're becoming a digital safety expert! 🌟",
          },
        ],
      },
    ],
  },
  {
    id: "financial",
    label: "Money & Taxes",
    emoji: "💰",
    description: "Budgeting, saving, investing, credit scores",
    image: financialBudgetingImg,
    lessons: [
      {
        id: 1,
        title: "Budgeting Basics",
        description: "Learn how to create and stick to a budget",
        steps: [
          {
            type: "info",
            title: "Why Budget?",
            content: "A budget is your financial roadmap. It tells your money where to go instead of wondering where it went. The 50/30/20 rule is a great starting point: 50% needs, 30% wants, 20% savings.",
            image: financialBudgetingImg,
            mascotMsg: "Let's master your money! 💰",
          },
          {
            type: "quiz",
            title: "Budget Categories",
            question: "Which expense is a 'need' rather than a 'want'?",
            options: ["Streaming subscription", "Groceries", "New sneakers", "Concert tickets"],
            correct: 1,
            explanation: "Groceries are a need — you must eat! Streaming, new shoes, and concerts are wants. The key is distinguishing between what you need to survive and what's nice to have.",
            mascotMsg: "Needs vs wants — the foundation of budgeting! 🤔",
          },
          {
            type: "info",
            title: "Tracking Your Spending",
            content: "For one month, write down every purchase. You'll be surprised where your money goes. Use apps like Mint, YNAB, or a simple spreadsheet. The goal isn't to restrict — it's to be aware.",
            mascotMsg: "Awareness is the first step! 📊",
          },
          {
            type: "drag",
            title: "Budget Setup Steps",
            instruction: "Put these budgeting steps in order:",
            items: [
              { id: "a", text: "Calculate your monthly income", order: 1 },
              { id: "b", text: "List all monthly expenses", order: 2 },
              { id: "c", text: "Categorize into needs/wants/savings", order: 3 },
              { id: "d", text: "Review and adjust monthly", order: 4 },
            ],
            mascotMsg: "Step by step — let's build that budget! 🧩",
          },
          {
            type: "quiz",
            title: "Emergency Fund",
            question: "How many months of expenses should an emergency fund ideally cover?",
            options: ["1 month", "3–6 months", "12 months", "It doesn't matter"],
            correct: 1,
            explanation: "Most financial experts recommend 3–6 months of living expenses. This gives you enough runway to handle most unexpected situations without going into debt.",
            mascotMsg: "Last one — finish strong! 🏁",
          },
        ],
      },
      {
        id: 2,
        title: "Understanding Credit Scores",
        description: "What affects your credit and how to improve it",
        steps: [
          {
            type: "info",
            title: "What is a Credit Score?",
            content: "A credit score is a number between 300-850 that represents your creditworthiness. Lenders use it to decide whether to give you loans and at what interest rate. A higher score = better terms.",
            mascotMsg: "Your credit score opens (or closes) doors! 🚪",
          },
          {
            type: "quiz",
            title: "Credit Factors",
            question: "What has the BIGGEST impact on your credit score?",
            options: ["How many credit cards you have", "Payment history", "Your income", "Your age"],
            correct: 1,
            explanation: "Payment history accounts for about 35% of your credit score. Always pay at least the minimum on time. Even one late payment can significantly hurt your score.",
            mascotMsg: "This one's important — think carefully! 💳",
          },
          {
            type: "info",
            title: "Credit Utilization",
            content: "Try to use less than 30% of your available credit. If your credit limit is $1,000, keep your balance below $300. This shows lenders you're responsible with credit.",
            mascotMsg: "The 30% rule is golden! ✨",
          },
          {
            type: "quiz",
            title: "Building Credit",
            question: "Which action will NOT help build your credit score?",
            options: [
              "Paying bills on time",
              "Checking your credit score frequently",
              "Keeping old accounts open",
              "Using a secured credit card",
            ],
            correct: 1,
            explanation: "Checking your score is a 'soft inquiry' — it doesn't affect your score, but it also doesn't build it. Active credit use and on-time payments build credit.",
            mascotMsg: "You're getting smarter about money! 🌟",
          },
        ],
      },
      {
        id: 3,
        title: "Intro to Investing",
        description: "Stocks, bonds, and compound interest explained simply",
        steps: [
          {
            type: "info",
            title: "Why Invest?",
            content: "Inflation means your money loses value sitting in a regular savings account. Investing lets your money grow faster than inflation. Thanks to compound interest, even small amounts grow significantly over time.",
            mascotMsg: "Make your money work for you! 📈",
          },
          {
            type: "quiz",
            title: "Investment Types",
            question: "Which investment type is generally the SAFEST?",
            options: ["Individual stocks", "Cryptocurrency", "Government bonds", "Options trading"],
            correct: 2,
            explanation: "Government bonds are backed by the government and are considered the safest investment. They offer lower returns but much less risk than stocks or crypto.",
            mascotMsg: "Risk vs reward — a key concept! 🎯",
          },
          {
            type: "info",
            title: "Compound Interest Magic",
            content: "If you invest $100/month starting at age 20 with 7% average returns, by age 60 you'd have about $264,000 — but you only put in $48,000! The rest is compound interest. Starting early is the biggest advantage.",
            mascotMsg: "Compound interest is truly magical! ✨",
          },
          {
            type: "quiz",
            title: "Diversification",
            question: "What does 'diversification' mean in investing?",
            options: [
              "Putting all money in one stock",
              "Spreading investments across different assets",
              "Only investing in your own company",
              "Changing investments daily",
            ],
            correct: 1,
            explanation: "Diversification means spreading your investments across different types of assets to reduce risk. Don't put all your eggs in one basket!",
            mascotMsg: "Great work on investing basics! 🎉",
          },
        ],
      },
    ],
  },
  {
    id: "health",
    label: "Health & Wellness",
    emoji: "🧘",
    description: "Exercise, mental health, sleep, nutrition basics",
    image: healthWellnessImg,
    lessons: [
      {
        id: 1,
        title: "Sleep Hygiene",
        description: "Better sleep for a better life",
        steps: [
          {
            type: "info",
            title: "Why Sleep Matters",
            content: "Adults need 7-9 hours of sleep. Poor sleep affects memory, mood, immune function, and even weight. Think of sleep as your body's maintenance mode — essential, not optional.",
            image: healthWellnessImg,
            mascotMsg: "Good sleep = good life! Let's learn how! 😴",
          },
          {
            type: "quiz",
            title: "Sleep Facts",
            question: "What should you avoid at least 1 hour before bed?",
            options: ["Reading a book", "Blue light from screens", "Light stretching", "Drinking water"],
            correct: 1,
            explanation: "Blue light from phones, tablets, and computers suppresses melatonin production, making it harder to fall asleep. Use night mode or stop screens 1 hour before bed.",
            mascotMsg: "Your bedtime routine matters! 📱🚫",
          },
          {
            type: "info",
            title: "Creating a Sleep Routine",
            content: "Go to bed and wake up at the same time every day — even weekends. Keep your room cool (65-68°F), dark, and quiet. Avoid caffeine after 2 PM and heavy meals before bed.",
            mascotMsg: "Consistency is the secret! 🌙",
          },
          {
            type: "drag",
            title: "Bedtime Routine",
            instruction: "Build the ideal bedtime routine in order:",
            items: [
              { id: "a", text: "Put away all screens", order: 1 },
              { id: "b", text: "Do light stretching or reading", order: 2 },
              { id: "c", text: "Dim the lights", order: 3 },
              { id: "d", text: "Practice deep breathing in bed", order: 4 },
            ],
            mascotMsg: "Build your perfect wind-down routine! 🌟",
          },
          {
            type: "quiz",
            title: "Sleep Myths",
            question: "Which statement about sleep is TRUE?",
            options: [
              "You can 'catch up' on sleep over the weekend",
              "Alcohol helps you sleep better",
              "Naps over 30 min can disrupt nighttime sleep",
              "Snoring is always harmless",
            ],
            correct: 2,
            explanation: "Long naps (over 30 minutes) can make it harder to fall asleep at night. Short power naps (15-20 min) are better if you need a midday boost.",
            mascotMsg: "Sleep smarter, not longer! 💤",
          },
        ],
      },
      {
        id: 2,
        title: "Mental Health Basics",
        description: "Understanding and caring for your mental wellbeing",
        steps: [
          {
            type: "info",
            title: "Mental Health is Health",
            content: "Just like physical health, mental health needs attention and care. It's normal to feel stressed, anxious, or down sometimes. What matters is recognizing when you need help and knowing how to get it.",
            mascotMsg: "Your mind deserves care too! 🧠💚",
          },
          {
            type: "quiz",
            title: "Stress Management",
            question: "Which is a healthy way to manage stress?",
            options: [
              "Ignoring it until it goes away",
              "Regular physical exercise",
              "Excessive social media scrolling",
              "Skipping meals to save time",
            ],
            correct: 1,
            explanation: "Exercise releases endorphins, natural mood boosters. Even a 20-minute walk can significantly reduce stress and anxiety levels.",
            mascotMsg: "Healthy coping strategies make all the difference! 💪",
          },
          {
            type: "info",
            title: "When to Seek Help",
            content: "Consider professional help if: feelings of sadness last more than 2 weeks, anxiety interferes with daily life, you're using substances to cope, or you're having thoughts of self-harm. There's no shame in asking for help.",
            mascotMsg: "Asking for help is a sign of strength! 🌈",
          },
          {
            type: "quiz",
            title: "Self-Care",
            question: "Which is an example of emotional self-care?",
            options: [
              "Working overtime every week",
              "Setting healthy boundaries with others",
              "Saying yes to everything",
              "Checking work emails at midnight",
            ],
            correct: 1,
            explanation: "Setting boundaries is crucial for emotional health. It's okay to say no. Protecting your time and energy is not selfish — it's necessary.",
            mascotMsg: "Boundaries = self-respect! You're doing great! 🌟",
          },
        ],
      },
    ],
  },
  {
    id: "career",
    label: "Career & Work",
    emoji: "📈",
    description: "Resumes, interviews, workplace communication",
    image: careerSkillsImg,
    lessons: [
      {
        id: 1,
        title: "Building a Great Resume",
        description: "Stand out with a professional resume",
        steps: [
          {
            type: "info",
            title: "Resume Basics",
            content: "Your resume is your first impression. Recruiters spend an average of 7 seconds scanning it. Use clear formatting, bullet points, and quantify your achievements (e.g., 'Increased sales by 20%').",
            image: careerSkillsImg,
            mascotMsg: "Let's make you stand out! 📄✨",
          },
          {
            type: "quiz",
            title: "Resume Do's and Don'ts",
            question: "What should you NEVER include on a resume?",
            options: [
              "Relevant skills and certifications",
              "Your age, marital status, or photo",
              "Quantified achievements",
              "Contact information",
            ],
            correct: 1,
            explanation: "In most countries, including personal details like age, marital status, or a photo can lead to bias. Focus on skills, experience, and achievements.",
            mascotMsg: "What to include (and what to skip)! 🤔",
          },
          {
            type: "drag",
            title: "Resume Sections",
            instruction: "Arrange these resume sections in the best order:",
            items: [
              { id: "a", text: "Contact information & summary", order: 1 },
              { id: "b", text: "Work experience", order: 2 },
              { id: "c", text: "Education", order: 3 },
              { id: "d", text: "Skills & certifications", order: 4 },
            ],
            mascotMsg: "Structure matters for first impressions! 📋",
          },
          {
            type: "quiz",
            title: "Action Words",
            question: "Which is the best way to describe a work achievement?",
            options: [
              "Was responsible for the team",
              "Led a team of 5 to deliver project 2 weeks early",
              "Did stuff at work",
              "Worked hard every day",
            ],
            correct: 1,
            explanation: "Use action verbs and specific numbers. 'Led a team of 5 to deliver project 2 weeks early' shows leadership, team size, and measurable results.",
            mascotMsg: "Action words make your resume pop! 🚀",
          },
        ],
      },
      {
        id: 2,
        title: "Acing Job Interviews",
        description: "Preparation, common questions, and body language",
        steps: [
          {
            type: "info",
            title: "Interview Preparation",
            content: "Research the company, practice the STAR method (Situation, Task, Action, Result) for behavioral questions, prepare 3-5 questions to ask, and do a mock interview with a friend.",
            mascotMsg: "Preparation is 90% of interview success! 🎯",
          },
          {
            type: "quiz",
            title: "Common Questions",
            question: "How should you answer 'Tell me about yourself'?",
            options: [
              "Share your entire life story from childhood",
              "Give a 2-minute professional summary relevant to the role",
              "Say 'It's all on my resume'",
              "Talk about your hobbies and pets",
            ],
            correct: 1,
            explanation: "Keep it professional, relevant, and concise. Cover your background, key skills, and why you're excited about this role. About 2 minutes is perfect.",
            mascotMsg: "The classic question — nail it every time! 💪",
          },
          {
            type: "info",
            title: "Body Language Tips",
            content: "Maintain eye contact, offer a firm handshake, sit up straight, and smile naturally. Avoid crossing your arms, fidgeting, or looking at your phone. Your body language speaks before you do.",
            mascotMsg: "Non-verbal cues matter a lot! 👀",
          },
          {
            type: "quiz",
            title: "After the Interview",
            question: "What should you do within 24 hours after an interview?",
            options: [
              "Call the interviewer repeatedly",
              "Send a thank-you email",
              "Post about it on social media",
              "Nothing — just wait",
            ],
            correct: 1,
            explanation: "A thoughtful thank-you email within 24 hours shows professionalism and reinforces your interest. Reference something specific from the conversation.",
            mascotMsg: "The follow-up can seal the deal! 📧",
          },
        ],
      },
    ],
  },
  {
    id: "cooking",
    label: "Cooking & Nutrition",
    emoji: "🍳",
    description: "Meal prep, balanced diets, kitchen basics",
    image: cookingNutritionImg,
    lessons: [
      {
        id: 1,
        title: "Kitchen Essentials",
        description: "Must-have tools and basic techniques",
        steps: [
          {
            type: "info",
            title: "Setting Up Your Kitchen",
            content: "You don't need expensive equipment! Start with: a good chef's knife, cutting board, one large pot, one skillet, measuring cups, and a wooden spoon. These cover 90% of home cooking needs.",
            image: cookingNutritionImg,
            mascotMsg: "Every chef starts somewhere! Let's begin! 🍳",
          },
          {
            type: "quiz",
            title: "Knife Safety",
            question: "What's the safest way to hold food while cutting?",
            options: [
              "Flat palm on top of the food",
              "Curl your fingers into a 'claw' shape",
              "Hold the food in the air",
              "Use a fork to hold it",
            ],
            correct: 1,
            explanation: "The 'claw grip' keeps your fingertips tucked under your knuckles, guiding the knife while protecting your fingers. It's the #1 kitchen safety technique.",
            mascotMsg: "Safety first in the kitchen! 🔪",
          },
          {
            type: "drag",
            title: "Cooking Order",
            instruction: "Put these cooking steps in the right order:",
            items: [
              { id: "a", text: "Read the entire recipe first", order: 1 },
              { id: "b", text: "Prep all ingredients (mise en place)", order: 2 },
              { id: "c", text: "Heat the pan/oven", order: 3 },
              { id: "d", text: "Start cooking", order: 4 },
            ],
            mascotMsg: "Organization is the secret to good cooking! 📋",
          },
          {
            type: "quiz",
            title: "Basic Techniques",
            question: "What's the difference between sautéing and frying?",
            options: [
              "They're exactly the same thing",
              "Sautéing uses less oil and higher heat with constant stirring",
              "Frying uses less oil",
              "Sautéing means cooking without heat",
            ],
            correct: 1,
            explanation: "Sautéing uses a small amount of oil over high heat with frequent stirring. Frying uses more oil. Both are essential techniques to master.",
            mascotMsg: "You're becoming a kitchen pro! 👨‍🍳",
          },
        ],
      },
      {
        id: 2,
        title: "Balanced Meal Planning",
        description: "Nutrition basics and weekly meal prep",
        steps: [
          {
            type: "info",
            title: "The Balanced Plate",
            content: "A balanced meal has: 1/2 plate vegetables and fruits, 1/4 plate lean protein (chicken, fish, beans), 1/4 plate whole grains (brown rice, quinoa). Add healthy fats like olive oil or avocado.",
            mascotMsg: "Eating well doesn't have to be complicated! 🥗",
          },
          {
            type: "quiz",
            title: "Nutrition Facts",
            question: "Which nutrient provides the most energy per gram?",
            options: ["Protein (4 cal/g)", "Carbohydrates (4 cal/g)", "Fat (9 cal/g)", "Fiber (0 cal/g)"],
            correct: 2,
            explanation: "Fat provides 9 calories per gram — more than double protein or carbs. This is why portion control with fatty foods matters, but healthy fats are still essential!",
            mascotMsg: "Fuel your body the right way! ⚡",
          },
          {
            type: "info",
            title: "Meal Prep Sunday",
            content: "Spend 2 hours on Sunday to prep lunches for the week. Cook a big batch of grains, roast vegetables, and prepare protein. Store in containers. You'll save time, money, and eat healthier.",
            mascotMsg: "Meal prep = life hack! 📦",
          },
          {
            type: "quiz",
            title: "Food Storage",
            question: "How long can cooked food safely stay in the fridge?",
            options: ["1 day", "3-4 days", "2 weeks", "Indefinitely"],
            correct: 1,
            explanation: "Most cooked foods are safe in the fridge for 3-4 days. After that, bacteria can grow to unsafe levels. When in doubt, freeze it!",
            mascotMsg: "Food safety is important! 🧊",
          },
        ],
      },
    ],
  },
  {
    id: "social",
    label: "People Skills",
    emoji: "🤝",
    description: "Communication, networking, conflict resolution",
    image: socialSkillsImg,
    lessons: [
      {
        id: 1,
        title: "Active Listening",
        description: "The most underrated communication skill",
        steps: [
          {
            type: "info",
            title: "What is Active Listening?",
            content: "Active listening means fully concentrating on what someone is saying, not just waiting for your turn to talk. It involves eye contact, nodding, paraphrasing, and asking clarifying questions.",
            image: socialSkillsImg,
            mascotMsg: "The best communicators are great listeners! 👂",
          },
          {
            type: "quiz",
            title: "Listening Skills",
            question: "Which is an example of active listening?",
            options: [
              "Planning your response while they talk",
              "Saying 'So what you're saying is...' to confirm understanding",
              "Checking your phone occasionally",
              "Changing the subject to your experience",
            ],
            correct: 1,
            explanation: "Paraphrasing shows you're engaged and helps ensure you understood correctly. It makes the other person feel heard and valued.",
            mascotMsg: "Listen to understand, not just to reply! 💬",
          },
          {
            type: "info",
            title: "Empathy in Conversations",
            content: "Empathy means understanding someone's feelings from their perspective. Instead of saying 'I know how you feel,' try 'That sounds really challenging. How are you handling it?' — this validates without assuming.",
            mascotMsg: "Empathy connects people deeply! 💚",
          },
          {
            type: "quiz",
            title: "Difficult Conversations",
            question: "What's the best approach when you disagree with someone?",
            options: [
              "Raise your voice to make your point",
              "Use 'I' statements: 'I feel...' instead of 'You always...'",
              "Give them the silent treatment",
              "Immediately point out why they're wrong",
            ],
            correct: 1,
            explanation: "'I' statements express your feelings without blaming. 'I feel frustrated when meetings run late' is much more productive than 'You always make meetings run late.'",
            mascotMsg: "Conflicts are opportunities for growth! 🌱",
          },
        ],
      },
    ],
  },
  {
    id: "home",
    label: "Home & DIY",
    emoji: "🏠",
    description: "Basic repairs, cleaning, organization",
    lessons: [
      {
        id: 1,
        title: "Basic Home Maintenance",
        description: "Simple fixes every homeowner should know",
        steps: [
          {
            type: "info",
            title: "Your Home Toolkit",
            content: "Every home needs: a hammer, screwdriver set (Phillips + flathead), pliers, adjustable wrench, tape measure, level, and duct tape. Keep a flashlight and batteries handy too.",
            mascotMsg: "Let's get handy around the house! 🔧",
          },
          {
            type: "quiz",
            title: "Quick Fixes",
            question: "What should you do FIRST if your toilet won't stop running?",
            options: [
              "Call a plumber immediately",
              "Check the flapper valve inside the tank",
              "Turn off the water main to the house",
              "Ignore it — it'll fix itself",
            ],
            correct: 1,
            explanation: "A running toilet is usually caused by a worn flapper valve — a $5 fix you can do yourself! Lift the tank lid, check if the flapper seals properly, and replace if needed.",
            mascotMsg: "Save money with DIY fixes! 💡",
          },
          {
            type: "info",
            title: "Seasonal Maintenance",
            content: "Change HVAC filters every 1-3 months. Test smoke detectors monthly. Clean gutters twice a year. Check for water leaks under sinks regularly. Small maintenance prevents expensive repairs.",
            mascotMsg: "Prevention saves thousands! 🏠",
          },
          {
            type: "quiz",
            title: "Safety First",
            question: "What should you always do before doing electrical work?",
            options: [
              "Wear rubber shoes",
              "Turn off the circuit breaker for that area",
              "Work with wet hands for better grip",
              "Just be really careful",
            ],
            correct: 1,
            explanation: "ALWAYS turn off the circuit breaker before any electrical work. Test with a voltage tester to confirm there's no power. Safety is non-negotiable with electricity.",
            mascotMsg: "Safety is rule #1 with home repairs! ⚡",
          },
        ],
      },
    ],
  },
  {
    id: "everyday",
    label: "Everyday Skills",
    emoji: "👟",
    description: "Time management, organization, life hacks",
    lessons: [
      {
        id: 1,
        title: "Time Management",
        description: "Get more done with less stress",
        steps: [
          {
            type: "info",
            title: "The Eisenhower Matrix",
            content: "Organize tasks into 4 quadrants: Urgent+Important (do now), Important+Not Urgent (schedule), Urgent+Not Important (delegate), Not Urgent+Not Important (eliminate). Most people spend too much time in quadrant 3.",
            mascotMsg: "Work smarter, not harder! ⏰",
          },
          {
            type: "quiz",
            title: "Productivity",
            question: "Which technique involves working in 25-minute focused blocks?",
            options: ["The 80/20 Rule", "The Pomodoro Technique", "Time blocking", "The 2-minute rule"],
            correct: 1,
            explanation: "The Pomodoro Technique: 25 minutes of focused work, then a 5-minute break. After 4 rounds, take a longer 15-30 minute break. It fights procrastination and builds momentum.",
            mascotMsg: "Small focused bursts = big results! 🍅",
          },
          {
            type: "info",
            title: "The 2-Minute Rule",
            content: "If something takes less than 2 minutes, do it now. Replying to an email, putting dishes away, filing a document — these tiny tasks pile up if postponed. Handle them immediately.",
            mascotMsg: "Don't let small tasks snowball! ⚡",
          },
          {
            type: "quiz",
            title: "Avoiding Burnout",
            question: "What's the MOST important thing for preventing burnout?",
            options: [
              "Working longer hours to finish faster",
              "Setting boundaries and taking regular breaks",
              "Drinking more coffee",
              "Multitasking to get more done",
            ],
            correct: 1,
            explanation: "Boundaries and breaks are essential. Schedule downtime like you schedule meetings. Your best work comes when you're rested and energized.",
            mascotMsg: "Balance is the key to sustainability! 🌟",
          },
        ],
      },
    ],
  },
  {
    id: "legal",
    label: "Legal Basics",
    emoji: "⚖️",
    description: "Contracts, rights, civic duties",
    lessons: [
      {
        id: 1,
        title: "Understanding Contracts",
        description: "Read the fine print like a pro",
        steps: [
          {
            type: "info",
            title: "Contracts 101",
            content: "A contract is a legally binding agreement. Before signing anything — a lease, employment offer, or subscription — always read the entire document. Pay attention to cancellation terms, fees, and your obligations.",
            mascotMsg: "Always read before you sign! 📜",
          },
          {
            type: "quiz",
            title: "Contract Red Flags",
            question: "Which is a red flag in a contract?",
            options: [
              "A clear cancellation policy",
              "Automatic renewal without notification",
              "Specific payment terms",
              "A defined end date",
            ],
            correct: 1,
            explanation: "Auto-renewal clauses can lock you in unexpectedly. Always look for how to cancel, any automatic renewals, and early termination fees before signing.",
            mascotMsg: "Protect yourself from sneaky clauses! 🔍",
          },
          {
            type: "info",
            title: "Your Tenant Rights",
            content: "As a renter, you have rights: habitable living conditions, privacy (landlord must give notice before entering), security deposit return timelines, and protection against unfair eviction. Know your local laws!",
            mascotMsg: "Knowledge is power — know your rights! ⚖️",
          },
          {
            type: "quiz",
            title: "Legal Documents",
            question: "Which document should every adult have?",
            options: [
              "A will or estate plan",
              "A business plan",
              "A published book",
              "A patent",
            ],
            correct: 0,
            explanation: "A will ensures your wishes are followed regarding your assets and dependents. It's not just for the wealthy — everyone benefits from having one.",
            mascotMsg: "Planning ahead protects your loved ones! 💚",
          },
        ],
      },
    ],
  },
  {
    id: "environment",
    label: "Environmental Awareness",
    emoji: "🌍",
    description: "Sustainability, recycling, eco-friendly living",
    lessons: [
      {
        id: 1,
        title: "Reduce, Reuse, Recycle",
        description: "Simple steps for a greener life",
        steps: [
          {
            type: "info",
            title: "The 3 R's Hierarchy",
            content: "Reduce first (buy less, waste less), then Reuse (repurpose items), and finally Recycle. Most people focus on recycling, but reducing consumption has the biggest environmental impact.",
            mascotMsg: "Small changes, big impact! 🌱",
          },
          {
            type: "quiz",
            title: "Recycling Facts",
            question: "Which item should NOT go in your recycling bin?",
            options: [
              "Clean cardboard boxes",
              "Greasy pizza boxes",
              "Empty aluminum cans",
              "Clean glass bottles",
            ],
            correct: 1,
            explanation: "Greasy pizza boxes contaminate recycling batches. Tear off the clean parts to recycle and compost or trash the greasy parts.",
            mascotMsg: "Recycling right makes a difference! ♻️",
          },
          {
            type: "info",
            title: "Easy Eco Swaps",
            content: "Use reusable water bottles, bring your own bags, choose products with less packaging, buy secondhand when possible, and switch to LED bulbs. These small changes add up to a big impact over time.",
            mascotMsg: "Every swap counts! 🌿",
          },
          {
            type: "quiz",
            title: "Carbon Footprint",
            question: "Which everyday action has the LARGEST carbon footprint?",
            options: [
              "Leaving lights on",
              "Eating meat daily",
              "Using a plastic straw",
              "Not recycling one can",
            ],
            correct: 1,
            explanation: "The meat industry is one of the largest contributors to greenhouse gases. Even reducing meat consumption by 1-2 days per week makes a significant impact.",
            mascotMsg: "You're becoming an eco-warrior! 🌍",
          },
        ],
      },
    ],
  },
  {
    id: "safety",
    label: "Personal Safety",
    emoji: "🛡️",
    description: "First aid, emergency preparedness, self-defense",
    lessons: [
      {
        id: 1,
        title: "First Aid Essentials",
        description: "What to do in common emergencies",
        steps: [
          {
            type: "info",
            title: "The ABCs of First Aid",
            content: "In any emergency: check Airway (is it clear?), Breathing (are they breathing?), Circulation (is there a pulse/severe bleeding?). Always call emergency services first, then provide first aid while waiting.",
            mascotMsg: "These skills can save lives! 🏥",
          },
          {
            type: "quiz",
            title: "Emergency Response",
            question: "What should you do FIRST when someone is choking?",
            options: [
              "Start CPR immediately",
              "Ask 'Are you choking?' — if they can't answer, begin the Heimlich maneuver",
              "Give them water to drink",
              "Pat them gently on the back",
            ],
            correct: 1,
            explanation: "First confirm they're choking (can they speak, cough, or breathe?). If not, stand behind them, place your fist above their navel, and perform upward thrusts.",
            mascotMsg: "Quick thinking saves lives! ⏱️",
          },
          {
            type: "info",
            title: "Your First Aid Kit",
            content: "Every home should have: bandages, antiseptic wipes, gauze, medical tape, tweezers, scissors, pain relievers, and an emergency blanket. Check expiration dates every 6 months.",
            mascotMsg: "Be prepared for anything! 🩹",
          },
          {
            type: "quiz",
            title: "Burns Treatment",
            question: "How should you treat a minor burn?",
            options: [
              "Apply butter or toothpaste",
              "Run cool (not cold) water over it for 10-20 minutes",
              "Pop any blisters that form",
              "Cover it tightly with a bandage immediately",
            ],
            correct: 1,
            explanation: "Cool running water is the best first treatment. Never use ice, butter, or toothpaste. After cooling, cover loosely with a sterile bandage.",
            mascotMsg: "Great job learning first aid! 🌟",
          },
        ],
      },
    ],
  },
  {
    id: "communication",
    label: "Communication Skills",
    emoji: "💬",
    description: "Public speaking, writing, presenting",
    lessons: [
      {
        id: 1,
        title: "Public Speaking Confidence",
        description: "Overcome fear and present with impact",
        steps: [
          {
            type: "info",
            title: "Why We Fear Public Speaking",
            content: "Fear of public speaking (glossophobia) affects up to 75% of people. The key insight: your audience wants you to succeed. They're rooting for you! Preparation and practice are the best antidotes.",
            mascotMsg: "Everyone gets nervous — even pros! Let's conquer it! 🎤",
          },
          {
            type: "quiz",
            title: "Presentation Tips",
            question: "What's the most effective way to start a presentation?",
            options: [
              "Apologize for being nervous",
              "Open with a compelling story or surprising fact",
              "Read your first slide word-by-word",
              "Start with 'So, um, today I'm going to talk about...'",
            ],
            correct: 1,
            explanation: "A strong opening hooks your audience. Use a story, statistic, or question. Never apologize for nervousness — the audience usually can't tell!",
            mascotMsg: "Start strong, finish stronger! 💪",
          },
          {
            type: "info",
            title: "The Rule of Three",
            content: "People remember things in threes. Structure your talk around 3 main points. Apple does this: 'The iPod. A phone. An internet communicator.' Simple, memorable, powerful.",
            mascotMsg: "Three is the magic number! ✨",
          },
          {
            type: "quiz",
            title: "Handling Nerves",
            question: "Which technique helps manage presentation anxiety?",
            options: [
              "Memorizing your script word-for-word",
              "Deep breathing exercises before you start",
              "Avoiding eye contact with the audience",
              "Speaking as fast as possible to finish quickly",
            ],
            correct: 1,
            explanation: "Deep breathing activates your parasympathetic nervous system, calming your fight-or-flight response. Try 4-7-8 breathing: inhale 4s, hold 7s, exhale 8s.",
            mascotMsg: "Breathe, believe, begin! 🌬️",
          },
        ],
      },
    ],
  },
];

export function getCourseById(id: string): Course | undefined {
  return COURSES.find(c => c.id === id);
}

export function getLessonContent(courseId: string, lessonId: number): Lesson | undefined {
  const course = getCourseById(courseId);
  return course?.lessons.find(l => l.id === lessonId);
}
