import digitalSecurityImg from "@/assets/lessons/digital-security.jpg";
import financialBudgetingImg from "@/assets/lessons/financial-budgeting.jpg";
import healthWellnessImg from "@/assets/lessons/health-wellness.jpg";
import careerSkillsImg from "@/assets/lessons/career-skills.jpg";
import cookingNutritionImg from "@/assets/lessons/cooking-nutrition.jpg";
import socialSkillsImg from "@/assets/lessons/social-skills.jpg";

export interface LessonStep {
  type: "info" | "quiz" | "drag";
  title: string;
  content?: string;
  image?: string;
  video?: string; // YouTube embed URL e.g. "https://www.youtube.com/embed/VIDEO_ID"
  question?: string;
  options?: string[];
  correct?: number;
  explanation?: string;
  instruction?: string;
  items?: { id: string; text: string; order: number }[];
  mascotMsg: string;
}

export interface Lesson {
  id: number;
  title: string;
  description: string;
  steps: LessonStep[];
}

export interface Course {
  id: string;
  label: string;
  emoji: string;
  description: string;
  lessons: Lesson[];
  image?: string;
}

export const COURSES: Course[] = [
  {
    id: "tech",
    label: "Digital Literacy",
    emoji: "💻",
    description: "Internet safety, using devices, online tools, email",
    image: digitalSecurityImg,
    lessons: [
      {
        id: 1,
        title: "Staying Safe Online",
        description: "Learn how to protect yourself on the internet",
        steps: [
          {
            type: "info",
            title: "Why Online Safety Matters",
            content: "Every time you go online, you leave a digital footprint. Hackers, scammers, and advertisers can use your data. Learning to protect yourself is one of the most important digital skills you can have.",
            image: digitalSecurityImg,
            mascotMsg: "Let's learn how to stay safe on the internet! 🛡️",
          },
          {
            type: "quiz",
            title: "Password Strength",
            question: "Which of these is the STRONGEST password?",
            options: ["password123", "MyDog'sName", "j7$kL9!mQ2@xP", "12345678"],
            correct: 2,
            explanation: "A strong password uses a mix of uppercase, lowercase, numbers, and symbols. It should be at least 12 characters and not based on personal info.",
            mascotMsg: "Time to test your knowledge! 🔐",
          },
          {
            type: "info",
            title: "Two-Factor Authentication (2FA)",
            content: "2FA adds an extra layer of security. Even if someone steals your password, they can't access your account without the second factor — usually a code sent to your phone or generated by an app like Google Authenticator.",
            video: "https://www.youtube.com/embed/hGRii5f_uSc",
            mascotMsg: "This is a game-changer for security! 📱",
          },
          {
            type: "drag",
            title: "Security Best Practices",
            instruction: "Put these security steps in order of priority:",
            items: [
              { id: "a", text: "Use unique passwords for each account", order: 1 },
              { id: "b", text: "Enable two-factor authentication", order: 2 },
              { id: "c", text: "Keep software updated", order: 3 },
              { id: "d", text: "Use a password manager", order: 4 },
            ],
            mascotMsg: "Order these from most to least important! 🧩",
          },
          {
            type: "quiz",
            title: "Phishing Awareness",
            question: "Which is a sign of a phishing email?",
            options: [
              "It comes from your bank's official domain",
              "It asks you to urgently click a link to verify your identity",
              "It has proper grammar and spelling",
              "It was expected based on a recent action you took",
            ],
            correct: 1,
            explanation: "Phishing emails create urgency to trick you into clicking malicious links. Always verify sender addresses and never click suspicious links.",
            mascotMsg: "Last question — you've got this! 🎯",
          },
        ],
      },
      {
        id: 2,
        title: "Using Email Effectively",
        description: "Master email etiquette and organization",
        steps: [
          {
            type: "info",
            title: "Email Basics",
            content: "Email is still the primary form of professional communication. A well-crafted email can open doors, while a poorly written one can close them. Let's learn the essentials of email communication.",
            mascotMsg: "Email skills are super important! 📧",
          },
          {
            type: "quiz",
            title: "Email Etiquette",
            question: "What should you always include in a professional email?",
            options: [
              "Emojis to be friendly",
              "A clear subject line",
              "Your entire life story",
              "Multiple fonts and colors",
            ],
            correct: 1,
            explanation: "A clear subject line helps the recipient understand the purpose of your email immediately. It's the first thing they see!",
            mascotMsg: "Think about what makes an email easy to read! 🤔",
          },
          {
            type: "info",
            title: "Managing Your Inbox",
            content: "Use the '4 D's method': Delete (spam/irrelevant), Do (takes under 2 minutes), Delegate (forward to the right person), or Defer (schedule for later). This keeps your inbox manageable.",
            mascotMsg: "Pro tip for inbox zero! 📋",
          },
          {
            type: "drag",
            title: "Parts of a Professional Email",
            instruction: "Put these email components in the correct order:",
            items: [
              { id: "a", text: "Subject line", order: 1 },
              { id: "b", text: "Greeting (Dear/Hi)", order: 2 },
              { id: "c", text: "Body (main message)", order: 3 },
              { id: "d", text: "Sign-off and signature", order: 4 },
            ],
            mascotMsg: "Structure matters! Put these in order! 📝",
          },
          {
            type: "quiz",
            title: "CC vs BCC",
            question: "When should you use BCC (Blind Carbon Copy)?",
            options: [
              "When you want everyone to see all recipients",
              "When sending to a large group where privacy matters",
              "Only for your boss",
              "Never — it's considered rude",
            ],
            correct: 1,
            explanation: "BCC protects recipients' email addresses from being visible to others. It's essential for mass emails and protecting privacy.",
            mascotMsg: "Almost done with email mastery! 🎉",
          },
        ],
      },
      {
        id: 3,
        title: "Navigating Social Media Safely",
        description: "Privacy settings, digital footprint, and responsible posting",
        steps: [
          {
            type: "info",
            title: "Your Digital Footprint",
            content: "Everything you post, like, share, or comment on creates a permanent digital footprint. Future employers, schools, and others can find this information. Think before you post!",
            mascotMsg: "Your online presence matters more than you think! 🌐",
          },
          {
            type: "quiz",
            title: "Privacy Settings",
            question: "What should you do FIRST when creating a new social media account?",
            options: [
              "Post your first photo",
              "Add all your friends",
              "Review and adjust privacy settings",
              "Share your location",
            ],
            correct: 2,
            explanation: "Always review privacy settings first. Set your profile to private, limit who can see your posts, and control who can tag you.",
            mascotMsg: "Privacy first! Always! 🔒",
          },
          {
            type: "info",
            title: "Recognizing Misinformation",
            content: "Before sharing news: Check the source (is it reputable?), look for the story on other outlets, check the date (is it current?), and read beyond the headline. If it sounds too outrageous, it might be fake.",
            mascotMsg: "Be a critical thinker online! 🧠",
          },
          {
            type: "quiz",
            title: "Safe Sharing",
            question: "Which of these is safe to share publicly on social media?",
            options: [
              "Your home address",
              "A photo of your vacation after you return",
              "Your daily routine and schedule",
              "Pictures of your credit card",
            ],
            correct: 1,
            explanation: "Sharing vacation photos after returning is safe. Never share locations in real-time, personal documents, or daily routines that could be used against you.",
            mascotMsg: "You're becoming a digital safety expert! 🌟",
          },
        ],
      },
    ],
  },
  {
    id: "financial",
    label: "Money & Taxes",
    emoji: "💰",
    description: "Budgeting, saving, investing, credit scores",
    image: financialBudgetingImg,
    lessons: [
      {
        id: 1,
        title: "Budgeting Basics",
        description: "Learn how to create and stick to a budget",
        steps: [
          {
            type: "info",
            title: "Why Budget?",
            content: "A budget is your financial roadmap. It tells your money where to go instead of wondering where it went. The 50/30/20 rule is a great starting point: 50% needs, 30% wants, 20% savings.",
            image: financialBudgetingImg,
            video: "https://www.youtube.com/embed/OZQQMYfaBT4",
            mascotMsg: "Let's master your money! 💰",
          },
          {
            type: "quiz",
            title: "Budget Categories",
            question: "Which expense is a 'need' rather than a 'want'?",
            options: ["Streaming subscription", "Groceries", "New sneakers", "Concert tickets"],
            correct: 1,
            explanation: "Groceries are a need — you must eat! Streaming, new shoes, and concerts are wants. The key is distinguishing between what you need to survive and what's nice to have.",
            mascotMsg: "Needs vs wants — the foundation of budgeting! 🤔",
          },
          {
            type: "info",
            title: "Tracking Your Spending",
            content: "For one month, write down every purchase. You'll be surprised where your money goes. Use apps like Mint, YNAB, or a simple spreadsheet. The goal isn't to restrict — it's to be aware.",
            mascotMsg: "Awareness is the first step! 📊",
          },
          {
            type: "drag",
            title: "Budget Setup Steps",
            instruction: "Put these budgeting steps in order:",
            items: [
              { id: "a", text: "Calculate your monthly income", order: 1 },
              { id: "b", text: "List all monthly expenses", order: 2 },
              { id: "c", text: "Categorize into needs/wants/savings", order: 3 },
              { id: "d", text: "Review and adjust monthly", order: 4 },
            ],
            mascotMsg: "Step by step — let's build that budget! 🧩",
          },
          {
            type: "quiz",
            title: "Emergency Fund",
            question: "How many months of expenses should an emergency fund ideally cover?",
            options: ["1 month", "3–6 months", "12 months", "It doesn't matter"],
            correct: 1,
            explanation: "Most financial experts recommend 3–6 months of living expenses. This gives you enough runway to handle most unexpected situations without going into debt.",
            mascotMsg: "Last one — finish strong! 🏁",
          },
        ],
      },
      {
        id: 2,
        title: "Understanding Credit Scores",
        description: "What affects your credit and how to improve it",
        steps: [
          {
            type: "info",
            title: "What is a Credit Score?",
            content: "A credit score is a number between 300-850 that represents your creditworthiness. Lenders use it to decide whether to give you loans and at what interest rate. A higher score = better terms.",
            video: "https://www.youtube.com/embed/wu8Ug3sCS5g",
            mascotMsg: "Your credit score opens (or closes) doors! 🚪",
          },
          {
            type: "quiz",
            title: "Credit Factors",
            question: "What has the BIGGEST impact on your credit score?",
            options: ["How many credit cards you have", "Payment history", "Your income", "Your age"],
            correct: 1,
            explanation: "Payment history accounts for about 35% of your credit score. Always pay at least the minimum on time. Even one late payment can significantly hurt your score.",
            mascotMsg: "This one's important — think carefully! 💳",
          },
          {
            type: "info",
            title: "Credit Utilization",
            content: "Try to use less than 30% of your available credit. If your credit limit is $1,000, keep your balance below $300. This shows lenders you're responsible with credit.",
            mascotMsg: "The 30% rule is golden! ✨",
          },
          {
            type: "quiz",
            title: "Building Credit",
            question: "Which action will NOT help build your credit score?",
            options: [
              "Paying bills on time",
              "Checking your credit score frequently",
              "Keeping old accounts open",
              "Using a secured credit card",
            ],
            correct: 1,
            explanation: "Checking your score is a 'soft inquiry' — it doesn't affect your score, but it also doesn't build it. Active credit use and on-time payments build credit.",
            mascotMsg: "You're getting smarter about money! 🌟",
          },
        ],
      },
      {
        id: 3,
        title: "Intro to Investing",
        description: "Stocks, bonds, and compound interest explained simply",
        steps: [
          {
            type: "info",
            title: "Why Invest?",
            content: "Inflation means your money loses value sitting in a regular savings account. Investing lets your money grow faster than inflation. Thanks to compound interest, even small amounts grow significantly over time.",
            mascotMsg: "Make your money work for you! 📈",
          },
          {
            type: "quiz",
            title: "Investment Types",
            question: "Which investment type is generally the SAFEST?",
            options: ["Individual stocks", "Cryptocurrency", "Government bonds", "Options trading"],
            correct: 2,
            explanation: "Government bonds are backed by the government and are considered the safest investment. They offer lower returns but much less risk than stocks or crypto.",
            mascotMsg: "Risk vs reward — a key concept! 🎯",
          },
          {
            type: "info",
            title: "Compound Interest Magic",
            content: "If you invest $100/month starting at age 20 with 7% average returns, by age 60 you'd have about $264,000 — but you only put in $48,000! The rest is compound interest. Starting early is the biggest advantage.",
            video: "https://www.youtube.com/embed/NuhVK4r-VQw",
            mascotMsg: "Compound interest is truly magical! ✨",
          },
          {
            type: "quiz",
            title: "Diversification",
            question: "What does 'diversification' mean in investing?",
            options: [
              "Putting all money in one stock",
              "Spreading investments across different assets",
              "Only investing in your own company",
              "Changing investments daily",
            ],
            correct: 1,
            explanation: "Diversification means spreading your investments across different types of assets to reduce risk. Don't put all your eggs in one basket!",
            mascotMsg: "Great work on investing basics! 🎉",
          },
        ],
      },
    ],
  },
  {
    id: "health",
    label: "Health & Wellness",
    emoji: "🧘",
    description: "Exercise, mental health, sleep, nutrition basics",
    image: healthWellnessImg,
    lessons: [
      {
        id: 1,
        title: "Sleep Hygiene",
        description: "Better sleep for a better life",
        steps: [
          {
            type: "info",
            title: "Why Sleep Matters",
            content: "Adults need 7-9 hours of sleep. Poor sleep affects memory, mood, immune function, and even weight. Think of sleep as your body's maintenance mode — essential, not optional.",
            image: healthWellnessImg,
            video: "https://www.youtube.com/embed/m2SVFx2mOEg",
            mascotMsg: "Good sleep = good life! Let's learn how! 😴",
          },
          {
            type: "quiz",
            title: "Sleep Facts",
            question: "What should you avoid at least 1 hour before bed?",
            options: ["Reading a book", "Blue light from screens", "Light stretching", "Drinking water"],
            correct: 1,
            explanation: "Blue light from phones, tablets, and computers suppresses melatonin production, making it harder to fall asleep. Use night mode or stop screens 1 hour before bed.",
            mascotMsg: "Your bedtime routine matters! 📱🚫",
          },
          {
            type: "info",
            title: "Creating a Sleep Routine",
            content: "Go to bed and wake up at the same time every day — even weekends. Keep your room cool (65-68°F), dark, and quiet. Avoid caffeine after 2 PM and heavy meals before bed.",
            mascotMsg: "Consistency is the secret! 🌙",
          },
          {
            type: "drag",
            title: "Bedtime Routine",
            instruction: "Build the ideal bedtime routine in order:",
            items: [
              { id: "a", text: "Put away all screens", order: 1 },
              { id: "b", text: "Do light stretching or reading", order: 2 },
              { id: "c", text: "Dim the lights", order: 3 },
              { id: "d", text: "Practice deep breathing in bed", order: 4 },
            ],
            mascotMsg: "Build your perfect wind-down routine! 🌟",
          },
          {
            type: "quiz",
            title: "Sleep Myths",
            question: "Which statement about sleep is TRUE?",
            options: [
              "You can 'catch up' on sleep over the weekend",
              "Alcohol helps you sleep better",
              "Naps over 30 min can disrupt nighttime sleep",
              "Snoring is always harmless",
            ],
            correct: 2,
            explanation: "Long naps (over 30 minutes) can make it harder to fall asleep at night. Short power naps (15-20 min) are better if you need a midday boost.",
            mascotMsg: "Sleep smarter, not longer! 💤",
          },
        ],
      },
      {
        id: 2,
        title: "Mental Health Basics",
        description: "Understanding and caring for your mental wellbeing",
        steps: [
          {
            type: "info",
            title: "Mental Health is Health",
            content: "Just like physical health, mental health needs attention and care. It's normal to feel stressed, anxious, or down sometimes. What matters is recognizing when you need help and knowing how to get it.",
            mascotMsg: "Your mind deserves care too! 🧠💚",
          },
          {
            type: "quiz",
            title: "Stress Management",
            question: "Which is a healthy way to manage stress?",
            options: [
              "Ignoring it until it goes away",
              "Regular physical exercise",
              "Excessive social media scrolling",
              "Skipping meals to save time",
            ],
            correct: 1,
            explanation: "Exercise releases endorphins, natural mood boosters. Even a 20-minute walk can significantly reduce stress and anxiety levels.",
            mascotMsg: "Healthy coping strategies make all the difference! 💪",
          },
          {
            type: "info",
            title: "When to Seek Help",
            content: "Consider professional help if: feelings of sadness last more than 2 weeks, anxiety interferes with daily life, you're using substances to cope, or you're having thoughts of self-harm. There's no shame in asking for help.",
            mascotMsg: "Asking for help is a sign of strength! 🌈",
          },
          {
            type: "quiz",
            title: "Self-Care",
            question: "Which is an example of emotional self-care?",
            options: [
              "Working overtime every week",
              "Setting healthy boundaries with others",
              "Saying yes to everything",
              "Checking work emails at midnight",
            ],
            correct: 1,
            explanation: "Setting boundaries is crucial for emotional health. It's okay to say no. Protecting your time and energy is not selfish — it's necessary.",
            mascotMsg: "Boundaries = self-respect! You're doing great! 🌟",
          },
        ],
      },
    ],
  },
  {
    id: "career",
    label: "Career & Work",
    emoji: "📈",
    description: "Resumes, interviews, workplace communication",
    image: careerSkillsImg,
    lessons: [
      {
        id: 1,
        title: "Building a Great Resume",
        description: "Stand out with a professional resume",
        steps: [
          {
            type: "info",
            title: "Resume Basics",
            content: "Your resume is your first impression. Recruiters spend an average of 7 seconds scanning it. Use clear formatting, bullet points, and quantify your achievements (e.g., 'Increased sales by 20%').",
            image: careerSkillsImg,
            video: "https://www.youtube.com/embed/99oIYKZh8gQ",
            mascotMsg: "Let's make you stand out! 📄✨",
          },
          {
            type: "quiz",
            title: "Resume Do's and Don'ts",
            question: "What should you NEVER include on a resume?",
            options: [
              "Relevant skills and certifications",
              "Your age, marital status, or photo",
              "Quantified achievements",
              "Contact information",
            ],
            correct: 1,
            explanation: "In most countries, including personal details like age, marital status, or a photo can lead to bias. Focus on skills, experience, and achievements.",
            mascotMsg: "What to include (and what to skip)! 🤔",
          },
          {
            type: "drag",
            title: "Resume Sections",
            instruction: "Arrange these resume sections in the best order:",
            items: [
              { id: "a", text: "Contact information & summary", order: 1 },
              { id: "b", text: "Work experience", order: 2 },
              { id: "c", text: "Education", order: 3 },
              { id: "d", text: "Skills & certifications", order: 4 },
            ],
            mascotMsg: "Structure matters for first impressions! 📋",
          },
          {
            type: "quiz",
            title: "Action Words",
            question: "Which is the best way to describe a work achievement?",
            options: [
              "Was responsible for the team",
              "Led a team of 5 to deliver project 2 weeks early",
              "Did stuff at work",
              "Worked hard every day",
            ],
            correct: 1,
            explanation: "Use action verbs and specific numbers. 'Led a team of 5 to deliver project 2 weeks early' shows leadership, team size, and measurable results.",
            mascotMsg: "Action words make your resume pop! 🚀",
          },
        ],
      },
      {
        id: 2,
        title: "Acing Job Interviews",
        description: "Preparation, common questions, and body language",
        steps: [
          {
            type: "info",
            title: "Interview Preparation",
            content: "Research the company, practice the STAR method (Situation, Task, Action, Result) for behavioral questions, prepare 3-5 questions to ask, and do a mock interview with a friend.",
            mascotMsg: "Preparation is 90% of interview success! 🎯",
          },
          {
            type: "quiz",
            title: "Common Questions",
            question: "How should you answer 'Tell me about yourself'?",
            options: [
              "Share your entire life story from childhood",
              "Give a 2-minute professional summary relevant to the role",
              "Say 'It's all on my resume'",
              "Talk about your hobbies and pets",
            ],
            correct: 1,
            explanation: "Keep it professional, relevant, and concise. Cover your background, key skills, and why you're excited about this role. About 2 minutes is perfect.",
            mascotMsg: "The classic question — nail it every time! 💪",
          },
          {
            type: "info",
            title: "Body Language Tips",
            content: "Maintain eye contact, offer a firm handshake, sit up straight, and smile naturally. Avoid crossing your arms, fidgeting, or looking at your phone. Your body language speaks before you do.",
            mascotMsg: "Non-verbal cues matter a lot! 👀",
          },
          {
            type: "quiz",
            title: "After the Interview",
            question: "What should you do within 24 hours after an interview?",
            options: [
              "Call the interviewer repeatedly",
              "Send a thank-you email",
              "Post about it on social media",
              "Nothing — just wait",
            ],
            correct: 1,
            explanation: "A thoughtful thank-you email within 24 hours shows professionalism and reinforces your interest. Reference something specific from the conversation.",
            mascotMsg: "The follow-up can seal the deal! 📧",
          },
        ],
      },
    ],
  },
  {
    id: "cooking",
    label: "Cooking & Nutrition",
    emoji: "🍳",
    description: "Meal prep, balanced diets, kitchen basics",
    image: cookingNutritionImg,
    lessons: [
      {
        id: 1,
        title: "Kitchen Essentials",
        description: "Must-have tools and basic techniques",
        steps: [
          {
            type: "info",
            title: "Setting Up Your Kitchen",
            content: "You don't need expensive equipment! Start with: a good chef's knife, cutting board, one large pot, one skillet, measuring cups, and a wooden spoon. These cover 90% of home cooking needs.",
            image: cookingNutritionImg,
            video: "https://www.youtube.com/embed/zxSXuoAeJS4",
            mascotMsg: "Every chef starts somewhere! Let's begin! 🍳",
          },
          {
            type: "quiz",
            title: "Knife Safety",
            question: "What's the safest way to hold food while cutting?",
            options: [
              "Flat palm on top of the food",
              "Curl your fingers into a 'claw' shape",
              "Hold the food in the air",
              "Use a fork to hold it",
            ],
            correct: 1,
            explanation: "The 'claw grip' keeps your fingertips tucked under your knuckles, guiding the knife while protecting your fingers. It's the #1 kitchen safety technique.",
            mascotMsg: "Safety first in the kitchen! 🔪",
          },
          {
            type: "drag",
            title: "Cooking Order",
            instruction: "Put these cooking steps in the right order:",
            items: [
              { id: "a", text: "Read the entire recipe first", order: 1 },
              { id: "b", text: "Prep all ingredients (mise en place)", order: 2 },
              { id: "c", text: "Heat the pan/oven", order: 3 },
              { id: "d", text: "Start cooking", order: 4 },
            ],
            mascotMsg: "Organization is the secret to good cooking! 📋",
          },
          {
            type: "quiz",
            title: "Basic Techniques",
            question: "What's the difference between sautéing and frying?",
            options: [
              "They're exactly the same thing",
              "Sautéing uses less oil and higher heat with constant stirring",
              "Frying uses less oil",
              "Sautéing means cooking without heat",
            ],
            correct: 1,
            explanation: "Sautéing uses a small amount of oil over high heat with frequent stirring. Frying uses more oil. Both are essential techniques to master.",
            mascotMsg: "You're becoming a kitchen pro! 👨‍🍳",
          },
        ],
      },
      {
        id: 2,
        title: "Balanced Meal Planning",
        description: "Nutrition basics and weekly meal prep",
        steps: [
          {
            type: "info",
            title: "The Balanced Plate",
            content: "A balanced meal has: 1/2 plate vegetables and fruits, 1/4 plate lean protein (chicken, fish, beans), 1/4 plate whole grains (brown rice, quinoa). Add healthy fats like olive oil or avocado.",
            mascotMsg: "Eating well doesn't have to be complicated! 🥗",
          },
          {
            type: "quiz",
            title: "Nutrition Facts",
            question: "Which nutrient provides the most energy per gram?",
            options: ["Protein (4 cal/g)", "Carbohydrates (4 cal/g)", "Fat (9 cal/g)", "Fiber (0 cal/g)"],
            correct: 2,
            explanation: "Fat provides 9 calories per gram — more than double protein or carbs. This is why portion control with fatty foods matters, but healthy fats are still essential!",
            mascotMsg: "Fuel your body the right way! ⚡",
          },
          {
            type: "info",
            title: "Meal Prep Sunday",
            content: "Spend 2 hours on Sunday to prep lunches for the week. Cook a big batch of grains, roast vegetables, and prepare protein. Store in containers. You'll save time, money, and eat healthier.",
            mascotMsg: "Meal prep = life hack! 📦",
          },
          {
            type: "quiz",
            title: "Food Storage",
            question: "How long can cooked food safely stay in the fridge?",
            options: ["1 day", "3-4 days", "2 weeks", "Indefinitely"],
            correct: 1,
            explanation: "Most cooked foods are safe in the fridge for 3-4 days. After that, bacteria can grow to unsafe levels. When in doubt, freeze it!",
            mascotMsg: "Food safety is important! 🧊",
          },
        ],
      },
    ],
  },
  {
    id: "social",
    label: "People Skills",
    emoji: "🤝",
    description: "Communication, networking, conflict resolution",
    image: socialSkillsImg,
    lessons: [
      {
        id: 1,
        title: "Active Listening",
        description: "The most underrated communication skill",
        steps: [
          {
            type: "info",
            title: "What is Active Listening?",
            content: "Active listening means fully concentrating on what someone is saying, not just waiting for your turn to talk. It involves eye contact, nodding, paraphrasing, and asking clarifying questions.",
            image: socialSkillsImg,
            mascotMsg: "The best communicators are great listeners! 👂",
          },
          {
            type: "quiz",
            title: "Listening Skills",
            question: "Which is an example of active listening?",
            options: [
              "Planning your response while they talk",
              "Saying 'So what you're saying is...' to confirm understanding",
              "Checking your phone occasionally",
              "Changing the subject to your experience",
            ],
            correct: 1,
            explanation: "Paraphrasing shows you're engaged and helps ensure you understood correctly. It makes the other person feel heard and valued.",
            mascotMsg: "Listen to understand, not just to reply! 💬",
          },
          {
            type: "info",
            title: "Empathy in Conversations",
            content: "Empathy means understanding someone's feelings from their perspective. Instead of saying 'I know how you feel,' try 'That sounds really challenging. How are you handling it?' — this validates without assuming.",
            mascotMsg: "Empathy connects people deeply! 💚",
          },
          {
            type: "quiz",
            title: "Difficult Conversations",
            question: "What's the best approach when you disagree with someone?",
            options: [
              "Raise your voice to make your point",
              "Use 'I' statements: 'I feel...' instead of 'You always...'",
              "Give them the silent treatment",
              "Immediately point out why they're wrong",
            ],
            correct: 1,
            explanation: "'I' statements express your feelings without blaming. 'I feel frustrated when meetings run late' is much more productive than 'You always make meetings run late.'",
            mascotMsg: "Conflicts are opportunities for growth! 🌱",
          },
        ],
      },
    ],
  },
  {
    id: "home",
    label: "Home & DIY",
    emoji: "🏠",
    description: "Basic repairs, cleaning, organization",
    lessons: [
      {
        id: 1,
        title: "Basic Home Maintenance",
        description: "Simple fixes every homeowner should know",
        steps: [
          {
            type: "info",
            title: "Your Home Toolkit",
            content: "Every home needs: a hammer, screwdriver set (Phillips + flathead), pliers, adjustable wrench, tape measure, level, and duct tape. Keep a flashlight and batteries handy too.",
            mascotMsg: "Let's get handy around the house! 🔧",
          },
          {
            type: "quiz",
            title: "Quick Fixes",
            question: "What should you do FIRST if your toilet won't stop running?",
            options: [
              "Call a plumber immediately",
              "Check the flapper valve inside the tank",
              "Turn off the water main to the house",
              "Ignore it — it'll fix itself",
            ],
            correct: 1,
            explanation: "A running toilet is usually caused by a worn flapper valve — a $5 fix you can do yourself! Lift the tank lid, check if the flapper seals properly, and replace if needed.",
            mascotMsg: "Save money with DIY fixes! 💡",
          },
          {
            type: "info",
            title: "Seasonal Maintenance",
            content: "Change HVAC filters every 1-3 months. Test smoke detectors monthly. Clean gutters twice a year. Check for water leaks under sinks regularly. Small maintenance prevents expensive repairs.",
            mascotMsg: "Prevention saves thousands! 🏠",
          },
          {
            type: "quiz",
            title: "Safety First",
            question: "What should you always do before doing electrical work?",
            options: [
              "Wear rubber shoes",
              "Turn off the circuit breaker for that area",
              "Work with wet hands for better grip",
              "Just be really careful",
            ],
            correct: 1,
            explanation: "ALWAYS turn off the circuit breaker before any electrical work. Test with a voltage tester to confirm there's no power. Safety is non-negotiable with electricity.",
            mascotMsg: "Safety is rule #1 with home repairs! ⚡",
          },
        ],
      },
    ],
  },
  {
    id: "everyday",
    label: "Everyday Skills",
    emoji: "👟",
    description: "Time management, organization, life hacks",
    lessons: [
      {
        id: 1,
        title: "Time Management",
        description: "Get more done with less stress",
        steps: [
          {
            type: "info",
            title: "The Eisenhower Matrix",
            content: "Organize tasks into 4 quadrants: Urgent+Important (do now), Important+Not Urgent (schedule), Urgent+Not Important (delegate), Not Urgent+Not Important (eliminate). Most people spend too much time in quadrant 3.",
            mascotMsg: "Work smarter, not harder! ⏰",
          },
          {
            type: "quiz",
            title: "Productivity",
            question: "Which technique involves working in 25-minute focused blocks?",
            options: ["The 80/20 Rule", "The Pomodoro Technique", "Time blocking", "The 2-minute rule"],
            correct: 1,
            explanation: "The Pomodoro Technique: 25 minutes of focused work, then a 5-minute break. After 4 rounds, take a longer 15-30 minute break. It fights procrastination and builds momentum.",
            mascotMsg: "Small focused bursts = big results! 🍅",
          },
          {
            type: "info",
            title: "The 2-Minute Rule",
            content: "If something takes less than 2 minutes, do it now. Replying to an email, putting dishes away, filing a document — these tiny tasks pile up if postponed. Handle them immediately.",
            mascotMsg: "Don't let small tasks snowball! ⚡",
          },
          {
            type: "quiz",
            title: "Avoiding Burnout",
            question: "What's the MOST important thing for preventing burnout?",
            options: [
              "Working longer hours to finish faster",
              "Setting boundaries and taking regular breaks",
              "Drinking more coffee",
              "Multitasking to get more done",
            ],
            correct: 1,
            explanation: "Boundaries and breaks are essential. Schedule downtime like you schedule meetings. Your best work comes when you're rested and energized.",
            mascotMsg: "Balance is the key to sustainability! 🌟",
          },
        ],
      },
    ],
  },
  {
    id: "legal",
    label: "Legal Basics",
    emoji: "⚖️",
    description: "Contracts, rights, civic duties",
    lessons: [
      {
        id: 1,
        title: "Understanding Contracts",
        description: "Read the fine print like a pro",
        steps: [
          {
            type: "info",
            title: "Contracts 101",
            content: "A contract is a legally binding agreement. Before signing anything — a lease, employment offer, or subscription — always read the entire document. Pay attention to cancellation terms, fees, and your obligations.",
            mascotMsg: "Always read before you sign! 📜",
          },
          {
            type: "quiz",
            title: "Contract Red Flags",
            question: "Which is a red flag in a contract?",
            options: [
              "A clear cancellation policy",
              "Automatic renewal without notification",
              "Specific payment terms",
              "A defined end date",
            ],
            correct: 1,
            explanation: "Auto-renewal clauses can lock you in unexpectedly. Always look for how to cancel, any automatic renewals, and early termination fees before signing.",
            mascotMsg: "Protect yourself from sneaky clauses! 🔍",
          },
          {
            type: "info",
            title: "Your Tenant Rights",
            content: "As a renter, you have rights: habitable living conditions, privacy (landlord must give notice before entering), security deposit return timelines, and protection against unfair eviction. Know your local laws!",
            mascotMsg: "Knowledge is power — know your rights! ⚖️",
          },
          {
            type: "quiz",
            title: "Legal Documents",
            question: "Which document should every adult have?",
            options: [
              "A will or estate plan",
              "A business plan",
              "A published book",
              "A patent",
            ],
            correct: 0,
            explanation: "A will ensures your wishes are followed regarding your assets and dependents. It's not just for the wealthy — everyone benefits from having one.",
            mascotMsg: "Planning ahead protects your loved ones! 💚",
          },
        ],
      },
    ],
  },
  {
    id: "environment",
    label: "Environmental Awareness",
    emoji: "🌍",
    description: "Sustainability, recycling, eco-friendly living",
    lessons: [
      {
        id: 1,
        title: "Reduce, Reuse, Recycle",
        description: "Simple steps for a greener life",
        steps: [
          {
            type: "info",
            title: "The 3 R's Hierarchy",
            content: "Reduce first (buy less, waste less), then Reuse (repurpose items), and finally Recycle. Most people focus on recycling, but reducing consumption has the biggest environmental impact.",
            mascotMsg: "Small changes, big impact! 🌱",
          },
          {
            type: "quiz",
            title: "Recycling Facts",
            question: "Which item should NOT go in your recycling bin?",
            options: [
              "Clean cardboard boxes",
              "Greasy pizza boxes",
              "Empty aluminum cans",
              "Clean glass bottles",
            ],
            correct: 1,
            explanation: "Greasy pizza boxes contaminate recycling batches. Tear off the clean parts to recycle and compost or trash the greasy parts.",
            mascotMsg: "Recycling right makes a difference! ♻️",
          },
          {
            type: "info",
            title: "Easy Eco Swaps",
            content: "Use reusable water bottles, bring your own bags, choose products with less packaging, buy secondhand when possible, and switch to LED bulbs. These small changes add up to a big impact over time.",
            mascotMsg: "Every swap counts! 🌿",
          },
          {
            type: "quiz",
            title: "Carbon Footprint",
            question: "Which everyday action has the LARGEST carbon footprint?",
            options: [
              "Leaving lights on",
              "Eating meat daily",
              "Using a plastic straw",
              "Not recycling one can",
            ],
            correct: 1,
            explanation: "The meat industry is one of the largest contributors to greenhouse gases. Even reducing meat consumption by 1-2 days per week makes a significant impact.",
            mascotMsg: "You're becoming an eco-warrior! 🌍",
          },
        ],
      },
    ],
  },
  {
    id: "safety",
    label: "Personal Safety",
    emoji: "🛡️",
    description: "First aid, emergency preparedness, self-defense",
    lessons: [
      {
        id: 1,
        title: "First Aid Essentials",
        description: "What to do in common emergencies",
        steps: [
          {
            type: "info",
            title: "The ABCs of First Aid",
            content: "In any emergency: check Airway (is it clear?), Breathing (are they breathing?), Circulation (is there a pulse/severe bleeding?). Always call emergency services first, then provide first aid while waiting.",
            video: "https://www.youtube.com/embed/Plse2FOkV4Q",
            mascotMsg: "These skills can save lives! 🏥",
          },
          {
            type: "quiz",
            title: "Emergency Response",
            question: "What should you do FIRST when someone is choking?",
            options: [
              "Start CPR immediately",
              "Ask 'Are you choking?' — if they can't answer, begin the Heimlich maneuver",
              "Give them water to drink",
              "Pat them gently on the back",
            ],
            correct: 1,
            explanation: "First confirm they're choking (can they speak, cough, or breathe?). If not, stand behind them, place your fist above their navel, and perform upward thrusts.",
            mascotMsg: "Quick thinking saves lives! ⏱️",
          },
          {
            type: "info",
            title: "Your First Aid Kit",
            content: "Every home should have: bandages, antiseptic wipes, gauze, medical tape, tweezers, scissors, pain relievers, and an emergency blanket. Check expiration dates every 6 months.",
            mascotMsg: "Be prepared for anything! 🩹",
          },
          {
            type: "quiz",
            title: "Burns Treatment",
            question: "How should you treat a minor burn?",
            options: [
              "Apply butter or toothpaste",
              "Run cool (not cold) water over it for 10-20 minutes",
              "Pop any blisters that form",
              "Cover it tightly with a bandage immediately",
            ],
            correct: 1,
            explanation: "Cool running water is the best first treatment. Never use ice, butter, or toothpaste. After cooling, cover loosely with a sterile bandage.",
            mascotMsg: "Great job learning first aid! 🌟",
          },
        ],
      },
    ],
  },
  {
    id: "communication",
    label: "Communication Skills",
    emoji: "💬",
    description: "Public speaking, writing, presenting",
    lessons: [
      {
        id: 1,
        title: "Public Speaking Confidence",
        description: "Overcome fear and present with impact",
        steps: [
          {
            type: "info",
            title: "Why We Fear Public Speaking",
            content: "Fear of public speaking (glossophobia) affects up to 75% of people. The key insight: your audience wants you to succeed. They're rooting for you! Preparation and practice are the best antidotes.",
            video: "https://www.youtube.com/embed/Ns_z4wEtdRM",
            mascotMsg: "Everyone gets nervous — even pros! Let's conquer it! 🎤",
          },
          {
            type: "quiz",
            title: "Presentation Tips",
            question: "What's the most effective way to start a presentation?",
            options: [
              "Apologize for being nervous",
              "Open with a compelling story or surprising fact",
              "Read your first slide word-by-word",
              "Start with 'So, um, today I'm going to talk about...'",
            ],
            correct: 1,
            explanation: "A strong opening hooks your audience. Use a story, statistic, or question. Never apologize for nervousness — the audience usually can't tell!",
            mascotMsg: "Start strong, finish stronger! 💪",
          },
          {
            type: "info",
            title: "The Rule of Three",
            content: "People remember things in threes. Structure your talk around 3 main points. Apple does this: 'The iPod. A phone. An internet communicator.' Simple, memorable, powerful.",
            mascotMsg: "Three is the magic number! ✨",
          },
          {
            type: "quiz",
            title: "Handling Nerves",
            question: "Which technique helps manage presentation anxiety?",
            options: [
              "Memorizing your script word-for-word",
              "Deep breathing exercises before you start",
              "Avoiding eye contact with the audience",
              "Speaking as fast as possible to finish quickly",
            ],
            correct: 1,
            explanation: "Deep breathing activates your parasympathetic nervous system, calming your fight-or-flight response. Try 4-7-8 breathing: inhale 4s, hold 7s, exhale 8s.",
            mascotMsg: "Breathe, believe, begin! 🌬️",
          },
        ],
      },
    ],
  },
  {
    id: "photography",
    label: "Photography",
    emoji: "📷",
    description: "Composition, lighting, phone photography tips",
    lessons: [
      {
        id: 1,
        title: "Composition Basics",
        description: "Frame stunning photos with simple rules",
        steps: [
          { type: "info", title: "The Rule of Thirds", content: "Imagine your frame divided into a 3×3 grid. Place your subject along the lines or at intersections — not dead center. This creates more dynamic, visually interesting photos.", mascotMsg: "Let's learn to see like a photographer! 📷" },
          { type: "quiz", title: "Composition Quiz", question: "Where should you place the horizon line for a dramatic sky?", options: ["In the center", "Along the bottom third", "Along the top third", "It doesn't matter"], correct: 1, explanation: "Placing the horizon on the bottom third gives more room to the sky, emphasizing dramatic clouds or sunsets.", mascotMsg: "Think about what you want to emphasize! 🌅" },
          { type: "info", title: "Leading Lines", content: "Roads, fences, rivers, and pathways naturally draw the viewer's eye through the image. Use these 'leading lines' to guide attention toward your main subject.", mascotMsg: "Lines are everywhere once you start looking! 🛤️" },
          { type: "quiz", title: "Lighting Basics", question: "What time of day produces the warmest, most flattering natural light?", options: ["High noon", "Golden hour (sunrise/sunset)", "Overcast midday", "Midnight"], correct: 1, explanation: "Golden hour — the hour after sunrise and before sunset — produces warm, soft light that flatters almost every subject.", mascotMsg: "Chase that golden light! ✨" },
        ],
      },
    ],
  },
  {
    id: "music",
    label: "Music Basics",
    emoji: "🎵",
    description: "Reading music, rhythm, instruments, ear training",
    lessons: [
      {
        id: 1,
        title: "Understanding Rhythm",
        description: "Feel the beat and keep time",
        steps: [
          { type: "info", title: "What is Rhythm?", content: "Rhythm is the pattern of sounds and silences in music. A time signature like 4/4 means 4 beats per measure. Clap along to your favorite song — you're already reading rhythm!", mascotMsg: "Feel the beat! 🥁" },
          { type: "quiz", title: "Time Signatures", question: "What does a 3/4 time signature mean?", options: ["3 beats per measure", "4 beats per measure", "3 measures per song", "Play 3 notes then rest"], correct: 0, explanation: "3/4 time has 3 beats per measure — it's the waltz rhythm: ONE-two-three, ONE-two-three.", mascotMsg: "Think waltz! 💃" },
          { type: "info", title: "Note Values", content: "A whole note lasts 4 beats, a half note lasts 2, a quarter note lasts 1, and an eighth note lasts half a beat. These building blocks create every rhythm you've ever heard.", mascotMsg: "Music is math you can dance to! 🎶" },
          { type: "quiz", title: "Rhythm Practice", question: "How many quarter notes fit in one measure of 4/4 time?", options: ["2", "3", "4", "8"], correct: 2, explanation: "4/4 time = 4 quarter-note beats per measure. That's why it's called 'common time' — it's the most widely used time signature.", mascotMsg: "You're getting the rhythm! 🎵" },
        ],
      },
    ],
  },
  {
    id: "gardening",
    label: "Gardening",
    emoji: "🌱",
    description: "Growing plants, composting, indoor gardens",
    lessons: [
      {
        id: 1,
        title: "Starting Your First Garden",
        description: "From seeds to harvest — beginner-friendly guide",
        steps: [
          { type: "info", title: "Choose Your Space", content: "No yard? No problem. Window boxes, balcony pots, or indoor herb gardens all work. Most vegetables need 6-8 hours of sunlight. Start small — 3-5 plants is plenty for beginners.", mascotMsg: "Everyone can garden! 🌻" },
          { type: "quiz", title: "Beginner Plants", question: "Which plant is easiest for a complete beginner to grow?", options: ["Orchids", "Basil", "Bonsai trees", "Venus flytraps"], correct: 1, explanation: "Basil is forgiving, grows quickly, and is useful in cooking. It thrives in pots on a sunny windowsill — perfect for beginners!", mascotMsg: "Start simple and build confidence! 🌿" },
          { type: "info", title: "Watering Basics", content: "The #1 beginner mistake is overwatering. Stick your finger 1 inch into the soil — if it's dry, water. If damp, wait. Most plants prefer deep, infrequent watering over daily sprinkles.", mascotMsg: "Less is often more with water! 💧" },
          { type: "quiz", title: "Soil Health", question: "What does composting do for your garden?", options: ["Makes soil more acidic", "Adds nutrients and improves drainage", "Kills all bacteria in soil", "Replaces the need for sunlight"], correct: 1, explanation: "Compost is 'black gold' — it enriches soil with nutrients, improves water retention, and feeds beneficial microorganisms.", mascotMsg: "Compost is nature's recycling! 🍂" },
        ],
      },
    ],
  },
  {
    id: "parenting",
    label: "Parenting Essentials",
    emoji: "👶",
    description: "Child development, positive discipline, routines",
    lessons: [
      {
        id: 1,
        title: "Positive Discipline",
        description: "Guide behavior without punishment",
        steps: [
          { type: "info", title: "What is Positive Discipline?", content: "Positive discipline focuses on teaching, not punishing. Instead of 'Don't run!' try 'Walking feet, please!' It sets clear boundaries while respecting the child's dignity and encouraging problem-solving.", mascotMsg: "Teaching, not punishing! 💛" },
          { type: "quiz", title: "Discipline Strategies", question: "What's more effective than timeout for a toddler tantrum?", options: ["Yelling louder", "Naming their emotion: 'You're frustrated because...'", "Ignoring them completely", "Giving in to stop the crying"], correct: 1, explanation: "Naming emotions teaches emotional intelligence. Children calm faster when they feel understood. 'You're upset because you wanted the toy' validates their feelings.", mascotMsg: "Emotions are okay — behavior can be guided! 🧠" },
          { type: "info", title: "Consistent Routines", content: "Children thrive on predictability. A consistent bedtime routine, meal times, and daily rhythm reduces anxiety and power struggles. Visual schedules work great for younger kids.", mascotMsg: "Routines = security for kids! 📋" },
          { type: "quiz", title: "Age-Appropriate Expectations", question: "At what age can most children start simple chores like picking up toys?", options: ["6 months", "Around 2-3 years", "5 years", "Only as teenagers"], correct: 1, explanation: "Toddlers (2-3) can help with simple tasks like putting toys in a bin. It builds responsibility and gives them a sense of contribution to the family.", mascotMsg: "Little helpers become responsible adults! 🌟" },
        ],
      },
    ],
  },
  {
    id: "travel",
    label: "Smart Travel",
    emoji: "✈️",
    description: "Planning trips, budgeting, packing, safety abroad",
    lessons: [
      {
        id: 1,
        title: "Trip Planning 101",
        description: "Plan like a pro without overspending",
        steps: [
          { type: "info", title: "Budget-First Planning", content: "Set your total budget first, then work backward: flights (40%), accommodation (30%), food & activities (30%). Use fare comparison sites, travel off-season, and book 6-8 weeks ahead for the best deals.", mascotMsg: "Smart planning = more trips! ✈️" },
          { type: "quiz", title: "Travel Hacks", question: "When are flights usually cheapest to book?", options: ["The day before", "6-8 weeks before departure", "6 months in advance", "On holidays"], correct: 1, explanation: "The sweet spot is typically 6-8 weeks before domestic flights and 2-3 months for international. Tuesdays and Wednesdays tend to have lower prices.", mascotMsg: "Timing is everything! 💰" },
          { type: "info", title: "Packing Smart", content: "Roll clothes instead of folding to save space. Pack a capsule wardrobe (mix-and-match pieces). Always carry essentials (meds, charger, ID) in your personal item. One week = one carry-on if you pack right.", mascotMsg: "Less luggage = less stress! 🧳" },
          { type: "quiz", title: "Travel Safety", question: "What should you do with important documents while traveling?", options: ["Keep originals and copies together", "Store digital copies in cloud + keep originals in hotel safe", "Leave them at home", "Post photos of them on social media"], correct: 1, explanation: "Keep originals in a hotel safe and store digital copies (photos) in the cloud. This way you have backups if anything is lost or stolen.", mascotMsg: "Stay safe out there! 🛡️" },
        ],
      },
    ],
  },
  {
    id: "pets",
    label: "Pet Care",
    emoji: "🐾",
    description: "Dog & cat care, vet visits, training basics",
    lessons: [
      {
        id: 1,
        title: "Responsible Pet Ownership",
        description: "What every pet parent needs to know",
        steps: [
          { type: "info", title: "Before You Adopt", content: "Pets are a 10-20 year commitment. Consider: Can you afford vet bills ($500-2,000/year)? Do you have time for walks and play? Does your living situation allow pets? Research the breed's needs before committing.", mascotMsg: "A pet is a lifetime friend — be ready! 🐕" },
          { type: "quiz", title: "Pet Health", question: "How often should a healthy adult dog visit the vet?", options: ["Only when sick", "At least once a year", "Every month", "Every 5 years"], correct: 1, explanation: "Annual checkups catch problems early. Vaccinations, dental checks, and preventive care keep your pet healthy and can save thousands in emergency vet bills.", mascotMsg: "Prevention is better than cure! 🩺" },
          { type: "info", title: "Basic Training", content: "Positive reinforcement (treats + praise) is the most effective training method. Keep sessions short (5-10 min), be consistent with commands, and never punish mistakes. Patience is your greatest tool.", mascotMsg: "Every pet can learn — with patience! 🎓" },
          { type: "quiz", title: "Pet Safety", question: "Which common food is toxic to dogs?", options: ["Carrots", "Plain rice", "Chocolate", "Blueberries"], correct: 2, explanation: "Chocolate contains theobromine, which is toxic to dogs. Dark chocolate is most dangerous. Other toxic foods include grapes, onions, and xylitol (sweetener).", mascotMsg: "Know what's safe for your furry friend! ⚠️" },
        ],
      },
    ],
  },
  {
    id: "mindfulness",
    label: "Mindfulness & Meditation",
    emoji: "🧘",
    description: "Meditation, breathing techniques, stress relief",
    lessons: [
      {
        id: 1,
        title: "Getting Started with Meditation",
        description: "Simple techniques anyone can learn",
        steps: [
          { type: "info", title: "What is Meditation?", content: "Meditation isn't about emptying your mind — it's about noticing your thoughts without judgment. Even 5 minutes daily reduces stress, improves focus, and enhances emotional regulation. Start small, be consistent.", mascotMsg: "Your calm journey starts here! 🧘" },
          { type: "quiz", title: "Meditation Myths", question: "Which statement about meditation is TRUE?", options: ["You need to sit cross-legged", "5 minutes a day can make a difference", "You must clear your mind completely", "It only works in silence"], correct: 1, explanation: "Even 5 minutes of daily meditation shows measurable benefits for stress reduction and focus. You can meditate in any comfortable position, and thoughts are normal!", mascotMsg: "Small steps, big impact! 🌟" },
          { type: "info", title: "Box Breathing", content: "Box breathing: Inhale for 4 seconds, hold for 4, exhale for 4, hold for 4. Repeat 4 times. Navy SEALs use this technique to stay calm under pressure. Try it before stressful situations.", mascotMsg: "Breathe your way to calm! 🌬️" },
          { type: "quiz", title: "Daily Practice", question: "When is the best time to meditate?", options: ["Only at midnight", "Whatever time you'll actually do it consistently", "Only after exercise", "Only on weekends"], correct: 1, explanation: "The best time is whenever you can stick to it. Morning, lunch break, or evening — consistency matters more than timing.", mascotMsg: "Make it a habit! ✨" },
        ],
      },
    ],
  },
  {
    id: "automotive",
    label: "Car Basics",
    emoji: "🚗",
    description: "Maintenance, tires, roadside emergencies",
    lessons: [
      {
        id: 1,
        title: "Essential Car Maintenance",
        description: "Keep your car running and avoid costly repairs",
        steps: [
          { type: "info", title: "Know Your Dashboard", content: "Warning lights are your car talking to you. Check engine (could be minor or serious), oil pressure (stop driving!), temperature (overheating), and battery. Learn what each light means in your owner's manual.", mascotMsg: "Your car speaks — learn its language! 🚗" },
          { type: "quiz", title: "Maintenance Schedule", question: "How often should you change your engine oil?", options: ["Every month", "Every 5,000-7,500 miles (or as manual states)", "Once a year regardless", "Only when the light comes on"], correct: 1, explanation: "Modern cars typically need oil changes every 5,000-7,500 miles, but check your owner's manual. Regular oil changes are the single best thing for engine longevity.", mascotMsg: "Oil is your engine's lifeblood! 🛢️" },
          { type: "info", title: "Tire Care", content: "Check tire pressure monthly (find the correct PSI on the driver's door sticker, not the tire). Rotate tires every 5,000-8,000 miles. The penny test: insert a penny head-first — if you see all of Lincoln's head, tires need replacing.", mascotMsg: "Good tires = safe driving! 🔧" },
          { type: "quiz", title: "Roadside Emergency", question: "What should you do FIRST if you get a flat tire on the highway?", options: ["Slam on the brakes", "Gradually slow down and pull safely to the shoulder", "Keep driving to the next exit", "Jump out of the car"], correct: 1, explanation: "Gradually reduce speed, turn on hazards, and pull to a safe, flat spot on the shoulder. Never brake suddenly — it can cause a blowout to become a spinout.", mascotMsg: "Stay calm and stay safe! 🛣️" },
        ],
      },
    ],
  },
  {
    id: "sewing",
    label: "Sewing & Mending",
    emoji: "🧵",
    description: "Buttons, hems, basic repairs, simple projects",
    lessons: [
      {
        id: 1,
        title: "Basic Clothing Repairs",
        description: "Fix clothes instead of replacing them",
        steps: [
          { type: "info", title: "Your Sewing Kit", content: "All you need to start: needles, thread (black, white, navy), scissors, pins, and a seam ripper. A small kit costs under $10 and will save you hundreds in clothing replacements and alterations.", mascotMsg: "A stitch in time saves nine! 🧵" },
          { type: "quiz", title: "Button Sewing", question: "What do you sew through the button holes to create a 'shank' (thread stem)?", options: ["A toothpick placed on top while sewing", "Nothing — sew flat against fabric", "A paperclip", "Hot glue"], correct: 0, explanation: "Place a toothpick on top of the button while sewing through the holes. Remove it after, then wrap thread around the stems. This creates space for the buttonhole fabric.", mascotMsg: "The toothpick trick is a game-changer! 🪡" },
          { type: "info", title: "Fixing a Hem", content: "Use a blind hem stitch for invisible repairs: fold the hem up, catch just 1-2 threads of the outer fabric, then slide the needle through the folded hem. The stitches should be nearly invisible from outside.", mascotMsg: "Invisible fixes look professional! ✨" },
          { type: "quiz", title: "Fabric Care", question: "What does a hand-wash-only label mean?", options: ["You must take it to a dry cleaner", "Wash gently in cool water with mild detergent", "It can go in the washing machine on delicate", "You should never wash it"], correct: 1, explanation: "Hand wash means gentle washing in cool/lukewarm water with mild detergent. Avoid wringing — press water out gently and lay flat to dry.", mascotMsg: "Treat your clothes right! 👕" },
        ],
      },
    ],
  },
  {
    id: "languages",
    label: "Language Learning",
    emoji: "🗣️",
    description: "Strategies, memory techniques, practice tips",
    lessons: [
      {
        id: 1,
        title: "How to Learn Any Language",
        description: "Proven strategies for language acquisition",
        steps: [
          { type: "info", title: "The Science of Language Learning", content: "Adults can learn languages effectively! The key is consistent exposure. Aim for 30 minutes daily rather than 3-hour weekend sessions. Your brain builds neural pathways through regular repetition, not cramming.", mascotMsg: "You CAN learn a new language! 🗣️" },
          { type: "quiz", title: "Learning Methods", question: "Which method is MOST effective for language learning?", options: ["Memorizing grammar rules first", "Immersive practice — listening, speaking, making mistakes", "Reading a dictionary", "Watching movies without subtitles from day one"], correct: 1, explanation: "Immersion and active use beats passive study. Speak from day one (even badly!), listen to native speakers, and embrace mistakes as learning opportunities.", mascotMsg: "Mistakes are your best teachers! 💪" },
          { type: "info", title: "Spaced Repetition", content: "Review new words at increasing intervals: after 1 day, 3 days, 1 week, 2 weeks, 1 month. Apps like Anki automate this. You'll retain 90%+ of vocabulary vs. 20% from simple re-reading.", mascotMsg: "Smart review = lasting memory! 🧠" },
          { type: "quiz", title: "Daily Practice", question: "What's the most important thing for language learning progress?", options: ["Natural talent", "Expensive courses", "Daily consistency, even 10 minutes", "Living abroad"], correct: 2, explanation: "Consistency trumps everything. Ten minutes every day builds stronger neural pathways than sporadic hour-long sessions. Make it a daily habit you enjoy.", mascotMsg: "Show up every day — that's the secret! 🌟" },
        ],
      },
    ],
  },
  {
    id: "digital-tools",
    label: "Productivity Tools",
    emoji: "⚙️",
    description: "Spreadsheets, docs, cloud storage, task managers",
    lessons: [
      {
        id: 1,
        title: "Spreadsheet Superpowers",
        description: "Master the basics of spreadsheets for work and life",
        steps: [
          { type: "info", title: "Why Spreadsheets?", content: "Spreadsheets aren't just for accountants. Track budgets, plan meals, organize job applications, compare products, or manage projects. Google Sheets is free and works on any device.", mascotMsg: "Spreadsheets are life organizers! 📊" },
          { type: "quiz", title: "Formulas 101", question: "What does the formula =SUM(A1:A10) do?", options: ["Counts cells A1 to A10", "Adds up all values from A1 to A10", "Averages values in A1 to A10", "Sorts A1 to A10"], correct: 1, explanation: "SUM adds all values in the specified range. It's the most-used formula. Other essentials: AVERAGE, COUNT, MAX, MIN, and IF.", mascotMsg: "Formulas are your superpower! ⚡" },
          { type: "info", title: "Organizing with Filters", content: "Use filters to sort and find data quickly. Select your header row → Data → Create Filter. Now you can sort alphabetically, by number, or filter to show only specific values. Essential for large datasets.", mascotMsg: "Find what you need in seconds! 🔍" },
          { type: "quiz", title: "Practical Uses", question: "Which is NOT a good use for a spreadsheet?", options: ["Tracking monthly expenses", "Writing a novel", "Comparing insurance quotes", "Planning a weekly meal schedule"], correct: 1, explanation: "Spreadsheets excel at structured data, comparisons, and calculations. For long-form writing, use a word processor or doc tool instead.", mascotMsg: "Right tool for the right job! 🛠️" },
        ],
      },
    ],
  },
  {
    id: "negotiation",
    label: "Negotiation Skills",
    emoji: "🤝",
    description: "Salary talks, buying, selling, conflict resolution",
    lessons: [
      {
        id: 1,
        title: "Negotiation Fundamentals",
        description: "Get better outcomes in any negotiation",
        steps: [
          { type: "info", title: "Everything is Negotiable", content: "Rent, salaries, bills, car prices — more things are negotiable than you think. The key: do your research, know your worth, and be willing to walk away. The person who cares least has the most power.", mascotMsg: "Let's unlock your negotiation skills! 🤝" },
          { type: "quiz", title: "Salary Negotiation", question: "When should you negotiate salary for a new job?", options: ["During the first interview", "After receiving a written offer", "Never — take what they offer", "Before applying"], correct: 1, explanation: "Wait for a written offer, then negotiate. You have the most leverage once they've decided they want you. Research market rates on Glassdoor/LinkedIn beforehand.", mascotMsg: "Know your worth! 💰" },
          { type: "info", title: "The BATNA Concept", content: "BATNA = Best Alternative To a Negotiated Agreement. Before any negotiation, know your plan B. If you're buying a car, research other options. A strong BATNA gives you confidence to walk away from bad deals.", mascotMsg: "Always have a Plan B! 🎯" },
          { type: "quiz", title: "Win-Win", question: "What makes a negotiation 'win-win'?", options: ["You get everything you want", "Both sides feel they gained value", "You trick the other side", "You split everything exactly 50/50"], correct: 1, explanation: "Win-win means both parties feel the outcome is fair and valuable. This builds long-term relationships and leads to better deals over time.", mascotMsg: "The best deals work for everyone! 🌟" },
        ],
      },
    ],
  },
  {
    id: "mental-models",
    label: "Critical Thinking",
    emoji: "🧠",
    description: "Logic, biases, decision-making frameworks",
    lessons: [
      {
        id: 1,
        title: "Cognitive Biases",
        description: "Recognize the tricks your brain plays on you",
        steps: [
          { type: "info", title: "What Are Cognitive Biases?", content: "Cognitive biases are systematic errors in thinking. Your brain uses mental shortcuts (heuristics) that sometimes lead you astray. Recognizing them is the first step to making better decisions.", mascotMsg: "Know your brain's blind spots! 🧠" },
          { type: "quiz", title: "Common Biases", question: "What is 'confirmation bias'?", options: ["Agreeing with everything", "Seeking info that supports what you already believe", "Confirming plans with friends", "Being overly confident"], correct: 1, explanation: "Confirmation bias makes us seek out information that confirms our existing beliefs while ignoring contradicting evidence. It affects everything from politics to personal decisions.", mascotMsg: "Challenge your own assumptions! 🔍" },
          { type: "info", title: "The Sunk Cost Fallacy", content: "You've watched 2 hours of a terrible movie. Should you stay because you've 'invested' time? No! Past costs shouldn't influence future decisions. Judge choices on future value, not past investment.", mascotMsg: "Don't throw good money after bad! 💡" },
          { type: "quiz", title: "Better Decisions", question: "What's the best way to fight your own biases?", options: ["Trust your gut always", "Actively seek opposing viewpoints", "Make faster decisions", "Ask people who agree with you"], correct: 1, explanation: "Deliberately seeking opposing viewpoints, considering 'what if I'm wrong?', and using frameworks for decisions helps counteract natural biases.", mascotMsg: "Great thinkers question themselves! ✨" },
        ],
      },
    ],
  },
  {
    id: "networking",
    label: "Professional Networking",
    emoji: "🔗",
    description: "Building connections, LinkedIn, mentorship",
    lessons: [
      {
        id: 1,
        title: "Building Your Network",
        description: "Authentic connections that advance your career",
        steps: [
          { type: "info", title: "Networking Isn't Sleazy", content: "Forget the image of forced handshakes and business cards. Real networking is building genuine relationships. Focus on how you can help others first. Value flows both ways in good networks.", mascotMsg: "Authentic connections matter most! 🔗" },
          { type: "quiz", title: "Networking Approach", question: "What's the best opening when meeting someone at a professional event?", options: ["'Can you help me get a job?'", "Ask about their work and listen with genuine interest", "'Let me tell you about myself...'", "Hand them your resume"], correct: 1, explanation: "People love talking about their work. Show genuine curiosity, ask thoughtful questions, and listen. The relationship builds naturally from there.", mascotMsg: "Be curious about people! 💬" },
          { type: "info", title: "Following Up", content: "After meeting someone, connect on LinkedIn within 48 hours with a personalized note: 'Great meeting you at [event]. I enjoyed our chat about [specific topic].' Keep the relationship warm with occasional check-ins.", mascotMsg: "The follow-up is where the magic happens! 📧" },
          { type: "quiz", title: "Online Presence", question: "What's the most important part of your LinkedIn profile?", options: ["A professional photo", "Your headline and summary", "Number of connections", "Endorsements from strangers"], correct: 1, explanation: "Your headline and summary are what people see first. Use them to tell your story and what value you bring — not just your job title.", mascotMsg: "Your online presence is your digital handshake! 🌐" },
        ],
      },
    ],
  },
  {
    id: "moving",
    label: "Moving & Relocation",
    emoji: "📦",
    description: "Planning moves, apartment hunting, settling in",
    lessons: [
      {
        id: 1,
        title: "Moving Like a Pro",
        description: "Stress-free strategies for your next move",
        steps: [
          { type: "info", title: "The Moving Timeline", content: "Start 8 weeks before: declutter and donate. 6 weeks: get quotes from movers. 4 weeks: start packing non-essentials. 2 weeks: change your address. 1 week: pack an 'essentials box' (toiletries, chargers, snacks, sheets).", mascotMsg: "A good plan makes moving manageable! 📦" },
          { type: "quiz", title: "Apartment Hunting", question: "What should you check BEFORE signing a lease?", options: ["Just the rent price", "Water pressure, outlets, cell signal, and neighborhood at night", "Only the square footage", "The building's Instagram page"], correct: 1, explanation: "Visit at different times of day. Test water pressure, count outlets, check phone signal, look for pests, and ask about utilities, parking, and maintenance response times.", mascotMsg: "Look beyond the listing photos! 🏠" },
          { type: "info", title: "Declutter Before You Move", content: "Moving is the perfect time to downsize. If you haven't used something in a year, donate or sell it. Less stuff = cheaper move, easier unpacking, and a fresh start. Be ruthless!", mascotMsg: "Less stuff = more freedom! ✨" },
          { type: "quiz", title: "Moving Day", question: "What should go in your 'Open First' box?", options: ["Winter coats", "Toilet paper, phone charger, snacks, sheets, and basic tools", "Old magazines", "Holiday decorations"], correct: 1, explanation: "Your first-night essentials: toilet paper, paper towels, trash bags, phone charger, snacks, water, sheets, pillow, and a basic tool kit. You'll thank yourself!", mascotMsg: "Pack smart, move easy! 🎯" },
        ],
      },
    ],
  },
  {
    id: "taxes",
    label: "Tax Filing",
    emoji: "🧾",
    description: "Filing taxes, deductions, deadlines, forms",
    lessons: [
      {
        id: 1,
        title: "Filing Your First Tax Return",
        description: "Demystifying tax season step by step",
        steps: [
          { type: "info", title: "Taxes Aren't Scary", content: "If you earned income, you likely need to file. Gather your W-2s (from employers) and 1099s (freelance/interest income). Free filing options exist for incomes under $79,000 through IRS Free File.", mascotMsg: "Let's make tax season painless! 🧾" },
          { type: "quiz", title: "Tax Basics", question: "What's the difference between a tax deduction and a tax credit?", options: ["They're the same thing", "A deduction reduces taxable income; a credit directly reduces tax owed", "Credits are for businesses only", "Deductions are illegal"], correct: 1, explanation: "A $1,000 deduction might save you $220 in taxes (at 22% bracket). A $1,000 credit saves you exactly $1,000. Credits are more valuable dollar-for-dollar!", mascotMsg: "Credits > deductions in value! 💡" },
          { type: "info", title: "Common Deductions", content: "Standard deduction ($13,850 single / $27,700 married in 2023) vs. itemizing. Most people take the standard deduction. Student loan interest, educator expenses, and HSA contributions are 'above-the-line' deductions anyone can take.", mascotMsg: "Don't leave money on the table! 💰" },
          { type: "quiz", title: "Deadlines", question: "When is the typical US federal tax filing deadline?", options: ["January 1", "April 15", "July 4", "December 31"], correct: 1, explanation: "April 15 is the standard deadline (may shift to the next business day if it falls on a weekend/holiday). You can file an extension for more time, but you still owe any taxes by April 15.", mascotMsg: "Mark your calendar! 📅" },
        ],
      },
    ],
  },
  {
    id: "insurance",
    label: "Insurance 101",
    emoji: "🏥",
    description: "Health, auto, renter's insurance explained",
    lessons: [
      {
        id: 1,
        title: "Understanding Insurance",
        description: "What you need, what you don't, and how to choose",
        steps: [
          { type: "info", title: "Insurance Basics", content: "Insurance is paying a small amount regularly (premium) to protect against large, unexpected costs. Key terms: premium (monthly cost), deductible (what you pay before insurance kicks in), copay (fixed cost per visit).", mascotMsg: "Protection against life's surprises! 🛡️" },
          { type: "quiz", title: "Health Insurance", question: "What does a 'deductible' mean?", options: ["Your monthly payment", "The amount you pay before insurance starts covering costs", "How much the insurance company profits", "A tax deduction"], correct: 1, explanation: "If your deductible is $1,500, you pay the first $1,500 of medical costs yourself. After that, insurance starts paying (usually sharing costs via copay/coinsurance).", mascotMsg: "Know your numbers! 📋" },
          { type: "info", title: "Renter's Insurance", content: "For ~$15/month, renter's insurance covers your belongings if stolen, damaged by fire/water, and provides liability protection if someone is injured in your home. It's one of the best insurance values available.", mascotMsg: "Protect your stuff for pennies a day! 🏠" },
          { type: "quiz", title: "Choosing Coverage", question: "Should you always choose the cheapest insurance plan?", options: ["Yes — save money wherever possible", "No — consider coverage, deductible, and network, not just premium", "Price is the only factor", "The most expensive is always best"], correct: 1, explanation: "A cheap premium with a $10,000 deductible could cost you more than a moderate premium with a $2,000 deductible. Balance monthly cost with what you'd pay in a worst-case scenario.", mascotMsg: "Cheap isn't always the best value! 💡" },
        ],
      },
    ],
  },
  {
    id: "writing",
    label: "Writing Skills",
    emoji: "✍️",
    description: "Clear writing, emails, reports, storytelling",
    lessons: [
      {
        id: 1,
        title: "Writing Clearly",
        description: "Communicate effectively in any format",
        steps: [
          { type: "info", title: "Clarity Over Cleverness", content: "Good writing is clear writing. Use short sentences. Avoid jargon. Write at a level anyone can understand. If a simpler word works, use it. The goal is communication, not showing off your vocabulary.", mascotMsg: "Clear writing is powerful writing! ✍️" },
          { type: "quiz", title: "Concise Writing", question: "Which sentence is better?", options: ["'Due to the fact that it was raining, we stayed inside'", "'Because it rained, we stayed inside'", "Both are equally good", "'The precipitation necessitated indoor relocation'"], correct: 1, explanation: "Cut filler phrases: 'due to the fact that' → 'because', 'in order to' → 'to', 'at this point in time' → 'now'. Fewer words = more impact.", mascotMsg: "Less is more! ✂️" },
          { type: "info", title: "The Inverted Pyramid", content: "Start with the most important information. Journalists use this: lead with the conclusion, then supporting details, then background. Your reader may stop at any point — make sure they get the key message first.", mascotMsg: "Lead with the headline! 📰" },
          { type: "quiz", title: "Proofreading", question: "What's the best way to proofread your own writing?", options: ["Read it immediately after writing", "Read it aloud after taking a break", "Trust spell-check completely", "Have someone else write it"], correct: 1, explanation: "Take a break (even 10 minutes), then read aloud. Your ears catch errors your eyes miss. Reading aloud also reveals awkward phrasing and run-on sentences.", mascotMsg: "Your ears are your best editor! 👂" },
        ],
      },
    ],
  },
  {
    id: "voting",
    label: "Civic Participation",
    emoji: "🗳️",
    description: "Voting, community involvement, knowing your rights",
    lessons: [
      {
        id: 1,
        title: "Your Civic Toolkit",
        description: "Engage with your community and make your voice heard",
        steps: [
          { type: "info", title: "Why Your Vote Matters", content: "Local elections often decide by hundreds or even dozens of votes. Your city council, school board, and local judges shape your daily life more than national politics. Show up for local elections — your vote has outsized impact.", mascotMsg: "Democracy starts locally! 🗳️" },
          { type: "quiz", title: "Voter Registration", question: "In most US states, what do you need to register to vote?", options: ["A college degree", "Valid ID and proof of address", "Property ownership", "A referral from a current voter"], correct: 1, explanation: "Requirements vary by state, but typically you need valid identification and proof of residency. Many states offer online registration. Check vote.org for your state's rules.", mascotMsg: "Registration is the first step! 📋" },
          { type: "info", title: "Beyond Voting", content: "Civic participation goes beyond voting: attend town halls, contact your representatives, join community boards, volunteer locally, or run for local office yourself. Democracy works best with active participants.", mascotMsg: "Get involved in your community! 🏘️" },
          { type: "quiz", title: "Know Your Rights", question: "Can your employer prevent you from voting?", options: ["Yes, work comes first", "No — most states require employers to provide time to vote", "Only if you're part-time", "Only during primaries"], correct: 1, explanation: "Most states have laws requiring employers to give employees time to vote. Check your state's specific laws — some require paid time off, others unpaid.", mascotMsg: "Know your rights and exercise them! ⚖️" },
        ],
      },
    ],
  },
];

export function getCourseById(id: string): Course | undefined {
  return COURSES.find(c => c.id === id);
}

export function getLessonContent(courseId: string, lessonId: number): Lesson | undefined {
  const course = getCourseById(courseId);
  return course?.lessons.find(l => l.id === lessonId);
}
