project_id = "rifvgveudfbphlcstioy"

[functions.process-email-queue]
verify_jwt = true

[functions.delete-user]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.tts]
verify_jwt = false

[functions.admin-manage-xp]
verify_jwt = false

[functions.friend-send-message]
verify_jwt = false

[functions.recommend-paths]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.adapt-lesson]
verify_jwt = false
